### ISSUE TITLE
Update permission prompt should opt-in to automatic installs

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1009]
Currently we prompt whether we should check for updates or not. I think we should add an option to also download and install for users who don't want to be bothered with any more update prompts.

I also think that not checking for updates at all is a dangerous option (users may be stuck without security updates, or the app may stop working after an OS upgrade), so we could also de-emphasise it.

The window could be something like this (wording to be bikeshedded)

<img src="https://cloud.githubusercontent.com/assets/72159/22133414/031ef488-deb8-11e6-98db-21cbf1bff911.png" width=520>

#901

**Comment by zorgiepoo** [comment]
I don't quite agree.

I'm not comfortable with encouraging a default of automatically installing updates in the background and in the past (and present) we've had trouble to get that option work properly (such that the manual check has *always* been more reliable of an option).

As for not checking for updates being a dangerous option, I'm not even sure I agree with that for most types of apps.

You may only be looking at one particular perspective to address #901. A less disruptive user interface for notifying of updates or not scheduling update checking after the first check are other possibilities.

**Comment by zorgiepoo** [comment]
Hm actually second thought maybe this isn't a bad idea.. I'm kind of wavering on this. I do like that don't check is de-emphasized.

I do think `master` currently suffers from major issues with the automatic installation option though, and it's not good enough yet to be an encouraged default. My fork tries to address those issues however.

**Comment by pornel** [comment]
Yes, possibly suggesting automatic as the default is too far (e.g. we don't have a way to show release notes and appcast can't override this #961). 

Another option would be to have a checkbox, although it might looks silly when the app also asks for a profile.

**Comment by zorgiepoo** [comment]
To add on, there are more "dangerous" things than an app not being updated. Like the updater acting faulty when trying to automatically install apps all the time, or downloading in the background when the user doesn't want it to occur on their poor connection and they can't figure out how to disable auto-updating.

Some applications have different updating policies than others. Some go by "notify user's of updates, but I won't be annoying since I won't distribute updates that often", others go by "distribute updates often, install silently", etc.. For one of my apps e.g., I have a policy of never disrupting the user: silently installing updates when possible; when it's not possible (i.e, authorization), then don't install updates automatically.

**Comment by zorgiepoo** [comment]
I'm handling this in #2209 / #2285 by adding a checkbox option to the dialog whose default value is based on what the developer initially specifies. As far as looking silly when app also asks for a profile I think it's still OK looking.
