### ISSUE TITLE
Getting Sparkle.framework versions upgraded

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1013]
I'd like all apps to use the latest version of Sparkle, but as far as I can see, that's not happening.

* Developers still support 10.6, so they're stuck with Sparkle 1.5/1.6.
* Developers copy Sparkle.framework to their project and forget about it.

Can we do something about it?

**Comment by zorgiepoo** [comment]
> Developers still support 10.6, so they're stuck with Sparkle 1.5/1.6.

I think we are totally dwarfed by Apple regarding this issue. They give a large incentive for developers to increase their minimum requirements. There may be a few exceptions, including apps that aren't very well maintained. Even cross platform apps like Chrome and Firefox have their minimum requirements set to 10.9. I don't think we have that much impact here. Instead, push responsibility over to Apple.

> Developers copy Sparkle.framework to their project and forget about it.

Yeah, that's a real issue, and affects all of my dependencies, not just Sparkle. I'm not sure if Cocoapods helps any here.

**Comment by pornel** [comment]
Cocoapods is probably good, since there's `pod update`, so there's no friction to updating. I guess we could make things marginally better by promoting Cocoapod install.

But for others? 

* Reach out to developers using Sparkle #717 and remind them to update?
  * What about apps that haven't got any updates in years? 
* Develop external updater? #1011 
  * Could the updater update Sparkle.framework only (after checking that its our stock build) without updating the parent app?
* Produce an app or script that scans for outdated Sparkle.framework copies and flags them, so that some users complain to authors?
* Is there something like greenkeeper.io for Cocoa?

**Comment by pornel** [comment]
* Set up a mailinglist for announcing new releases?

**Comment by zorgiepoo** [comment]
> Could the updater update Sparkle.framework only (after checking that its our stock build) without updating the parent app?

No, you'll invalidate code signing, which could also affect the application's behavior. Doesn't really seem like a great practice too..

**Comment by zorgiepoo** [comment]
Of course we'd also want to think about what has changed in Sparkle between the old version a developer may have installed and the newer version available. If it's just little bug fixes or enhancements? May not even be worth flagging developers individually. If there's a major security vulnerability or app corruption fix -- that could be worthy indeed.

**Comment by invariant** [comment]
As one of the offending culprits (I haven't updated Sparkle in my apps for _years_), the reason for it is simply that

1. The version that I have works perfectly and has done for years;
2. I'm scared that if I update it I will overlook some minor change to signing or config or _something_ that will break updates for my apps in the wild;
2. I don't know of any good reason to update*

*That isn't to say there aren't good reasons; there might be , I just don't know what they are.
