### ISSUE TITLE
On Sparkle and SHA-1

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1042]
There is a SHA-1 collision: https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html

First, please note there's a difference between a collision attack and a preimage attack. A collision allows attacker to create two new files that are different, but hash to the same value, but the attacker does not control the hash value. 

Collisions do not allow attackers to create files that hash to a specific value of an existing file. That is a preimage attack, which is much much harder, and currently there are no know weaknesses in SHA-1 of that type.

Sparkle uses SHA-1 as part of its DSA signature verification, so it is affected, but only in a limited way:

* The collision attack does not allow bypassing of DSA verification of any old release, because that would require a preimage attack.
* The collision attack does not allow bypassing of DSA verification without tricking the developer into including an attacker-controlled file in a very specific way.
* Sparkle has additional ways of verifying update integrity, such as Apple Code Signing and checksums in archives, and an attacker can't bypass verification without also finding a way bypass all the other layers at the same time, all within restrictions of what SHA-1 collision allows.

The collisions might be exploited in a very specific scenario, if all conditions are met:

* The attacker would have to spend 65 centuries of CPU time to prepare a pair of files with SHA-1 collision, so that one seems innocent and the other is malicious. However, both files would have to contain the malicious payload, since the collision attack only allows changing a few bytes.
* The attacker would have to trick the developer into including the specific attacker-controlled binary file in the app in a way that allows it to execute code.  
* The developer would have to include attacker's file as the very first file in the archive, uncompressed. If the malicious file is compressed, or the archive contains any unguessable data before the malicious file, the attack won't be possible.
* The attacker would then have to find a way to replace the colliding fragment of the update archive in a way that makes it malicious, but without breaking archive's compression, checksums, and Apple Code Signing of the payload.
* The attacker would then have to perform MITM attack on users of the application, also bypassing HTTPS if the app requires it.

---

From app authors perspective this does not change much:

* Don't include unverified files from untrusted sources in your app.
* Use HTTPS.
* Use Apple Code Signing and DSA signatures (an update with a DSA check is still better than without it).

---

This particular SHA-1 collision [is detectable](https://github.com/cr-marcstevens/sha1collisiondetection), so we can add a check for it in the code signing tools.

**Comment by riastradh-brave** [comment]
The criteria you list are not all as far-fetched as they may sound on their face.

- Anyone can take the shattered.it collision, or any other collision, and append a common suffix to generate another collision with no computational effort.
- In many file formats, it is easy to conceal two completely different versions of structured documents, sometimes even multiple different file formats as polyglots, using pointers or ignored padding in headers.  One could conceivably use the distinct prefixes of a SHA-1 collision as pointers to different parts of a file.
  - [Example of a related idea](https://www.blackhat.com/docs/eu-14/materials/eu-14-Apvrille-Hide-Android-Applications-In-Images-wp.pdf), obscuring a malicious Android APK as ciphertext in an innocuous-looking JPEG.

Further, as I understand it, according to https://sparkle-project.org/documentation/#apple-code-signing (retrieved 2018-04-23), a DSA signature alone is sufficient to persuade a client to apply a binary delta update, with no Apple code signature:

> If you both code-sign your application and include a public DSA key for signing your update archive, Sparkle allows issuing a new update that changes either your code signing certificate or your DSA keys. Note however this is a last resort and should _only_ be done if you lose access to one of them.

This suggests to me that the proposed mitigation of using Apple code signing is not enough to thwart forgery of binary delta updates.

Finally, the use of SHA-1 is a red flag for security practices, and makes auditing for bad crypto harder.  It is possible to use SHA-1 safely for limited applications, but an auditor's job is easier if there's no SHA-1 anywhere involved.  We're considering using Sparkle in an application, but we need to review our candidate dependencies for security first.  If we didn't have to scrutinize the use of SHA-1 carefully, we would be more inclined to adopt Sparkle, and I'm sure we're not alone in this.

Would you please consider prioritizing the replacement of SHA-1 so that nobody has to worry about these things?

**Comment by kornelski** [comment]
No, it's the opposite. I'm entertaining crypto nerd science-fiction scenarios here. Real-world usefulness of the shattered attack for Sparkle attacks is exactly zero.

* Shattered doesn't allow inserting/replacing of arbitrary data, but only toggling of a few pseudorandom bits in one block, too little for the change to be malware itself. This means the attacker has to convince the victim to ship a file that *already contains malware* that is ready to run. It's not possible to add the malware later. **The app author has to willingly add the malware payload themselves**. If you can convince authors to put your obfuscated malware in their executables, you've already won. You don't have to bother with the whole SHA Rube Goldberg machine.

 * Hash is verified against uncompressing archive. Compressed data is very fragile (a single bit flip is likely to make decoder go out of sync and turn the rest of file or archive into garbage), so it's already *extremely* hard to spray the data with shattered bit flips in a way that makes any sense whatsoever. On top of that archives have CRC. Even though CRC is weak if attacked directly, shattered can't do that. It can't replace 4 bytes in a specific location with a specific value. So in practice you spend $X0000 USD on a **lottery ticket with at best 1:2147483648 chance of winning**. And you can't even spend 20 trillion dollars to brute force-it — you get only one try per one app version. 

 * **You can't reuse the known PDF attack**. Even though it's possible to intentionally make a hybrid PDF-ZIP, app authors aren't going to "accidentally" inject known shattered prefix into a specially crafted archive. They just use regular zip/tar/dmg archiver, which can't be attacked with the known prefix (not even if you trick them into putting that PDF *in* the ZIP).
  If you're going to spend $50K on the attack, it's cheaper to buy a popular open-source library and backdoor it. That's how browser extensions get malware.
 
 * Attacker has to predict and compute the entire shattered prefix of the archive all the way up the place where bits are flipped, and known where the payload will be. It's going to be in an archive created by the author, and not the attacker. *Even if* attacker convinces victim to embed malware in their app, the attacker still has to guess all of archive's entropy. If you'll make code change they didn't guess? The attack is thwarted. You compress the archive one second later than the attacker guessed? The attack is thwarted.

And even if you succeed with social engineering and spend money on computing prefix that has lower expected value than regular lottery tickets, you *still* can't do anything with it! You have to break TLS or hack the server to even have a chance of delivering your hacked version.

This attack requires social engineering to work, so you can ignore the incredibly impossible crypto porn part, and focus on the social engineering step. Make a trojan horse that steals private keys — both Sparkle's and SSH's. That's *so* much simpler. It can be anything — cool screen saver at product hunt, Rust-Electron app submitted to Hackernews, or an npm package that prints animated unicorns in the console. You'll get *thousands* of private keys in a day, for $0.

**Comment by zorgiepoo** [comment]
Addressed by supporting EdDSA a while back right?
