### ISSUE TITLE
Change wording on read-only-volume error

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#1057]
These days users are more likely to run into app translocation (#1012) than use software from a DVD disc.

The error message needs to be updated.

**Comment by kainjow** [comment]
+1, just ran into this with the Sparkle test app, and was confused for a moment.

Technically, if an update was a Learn More update, the read-only issue doesn't apply. Maybe it could be smarter and only show this dialog when an actual auto-update is available.

**Comment by pornel** [comment]
Done in 55be13ca6faec96ba00164b37a17f5351b7b1b97

**Comment by cortig** [comment]
It seems that the same issue arises when the app is launched from a subfolder of /Applications.
I know ~/Downloads gets a special “read-only” treatment when apps are launched from there but is it the same type of situations in subfolders in /Applications?
In any case, at the bare minimum, the warning should be rewritten: it was really misleading for me to see a warning asking me not to run from ~/Downloads when the app was precisely not in the Downloads folder.

**Comment by cortig** [comment]
@zorgiepoo, it's not necessarily a matter of how the app is being distributed. If you drag the app from a signed .dmg to a subfolder inside /Applications (instead of the /Applications folder itself), and try to launch the update mechanism, you get the warning telling you it can't be updated because it's in the Downloads folder (which, clearly, is not accurate in this specific case).
