### ISSUE TITLE
Clients polling frequently

### ISSUE THREAD

**Issue by herf** [sparkle-project/Sparkle#1061]
Bug #835 is still occurring.

We rolled a f.lux update with Sparkle 1.16.0 and the frequent polling is still happening. 
(Our script just blocked a client polling 13 times a second.)

**Comment by pornel** [comment]
I've seen this too, but with only one client. It's almost 1 in a million, so I suspect it's due to someone's system being extremely weird/broken.

The solution might be to add some sanity checks, e.g. whether user defaults store the data, or maybe some in-process request limit.

**Comment by jkbullard** [comment]
"Locking" the ~/Library/Preferences/XXXXXX.plist file (using the checkbox in "Get Info") could cause exactly the behavior that we're seeing, is easy, and is something that a "one in a hundred thousand" users might do.

I was thinking about ways a user might want to fiddle with preferences, and decided one thing they might want to do is set them to "read only" to avoid making unintended changes. One way to set a file "read only" is to lock it in the "Get Info" dialog. If that's done and the application sets a default, reading it back gets the old value, at least sometimes. And a message like the following shows up in the Console log:

>10/4/17 9:26:29.788 AM cfprefsd[356]: CFPreferences: error renaming file /Users/....plist.9EBxauG to /Users....plist.

Looking at SUUpdater's updateDriverDidFinish:
```- (void)updateDriverDidFinish:(NSNotification *)note
{
	if ([note object] == self.driver && [self.driver finished])
	{
        self.driver = nil;
        [self updateLastUpdateCheckDate];
        [self scheduleNextUpdateCheck];
    }
}
```
I think what is happening is that between `[self updateLastUpdateCheckDate]` and `[self scheduleNextUpdateCheck]`, macOS saves the change in a temporary file, but then fails to rename the temp file, so it restores the defaults to the values from the (original, unmodified) file -- including the original value for `lastUpdateCheckDate`.

That would mean that `[self scheduleNextUpdateCheck]` uses the **old** value. Since the old value is "long ago" (sometime before the file was locked), it schedules the next update check to be run immediately. When that update finishes, updateDriverDidFinish is invoked again and the cycle repeats.

I tried to reproduce the frequent polling on a test computer, but couldn't. However, the behavior would be subject to the load on the computer, so it can't necessarily be reproduced easily. Maybe if the computer was very busy, macOS wouldn't have time to run the code that reverts the value quickly enough, and all would be well. Or maybe if the computer had a light load, 
`[self updateLastUpdateCheckDate]` and `[self scheduleNextUpdateCheck]` would be invoked immediately one after the other, and all would be well. In other words, its a race condition.

This unexpected (by me, anyway) behavior of NSUserDefaults may have implications beyond this one situation/variable in Sparkle ; I'll have to look at my application's other uses of defaults, too.

Fixing this in Sparkle would could involve using an SUUpdater class variable to hold the scheduleNextUpdateCheck value (reading it from defaults during the init of the class instance and setting it in defaults each time it is modified).

Other Sparkle use of defaults as if they were variables should also be looked into.
