### ISSUE TITLE
Provide a public API to check if a silent update is possible

### ISSUE THREAD

**Issue by tfar** [sparkle-project/Sparkle#1069]
When a non-admin user runs an app from /Applications, Sparkle update will pop-up an authentication dialog during the update process. It would be nice if there was a public API to detect if an update requires authentication of the end user so the application can choose to provide a different update strategy in this case, like manually prompting the user to do an update or moving the application to ~/Applications on first run.

**Comment by pornel** [comment]
First, I see two different cases here:

1. Update is possible, but requires admin privileges (app is in /Applications)
2. Update is not possible, because the app is quarantined (app is in ~/Downloads)

For the case (2) we're have detection and a prompt already (it just needs better text #923).

For the case (1), what the app can do better than Sparkle?

**Comment by tfar** [comment]
Right. I'm currently mostly concerned about case (1). In our app Sparkle causes an authentication dialog at exit of the application (when the usual silent update happens), i.e. https://www.dropbox.com/s/ck1ehmo72oag76b/swift.png?dl=0 . For the user it's not obvious that this dialog belongs to our application, as the icon is different and the application name isn't mentioned anywhere.

This is why ideally we'd like to detect if a silent update is possible, and if not disable silent updates so it's more obvious for the user that an update takes place.

Another useful application of the API would be to check silent install possibility on first run, and if it's not possible, popup a dialog that recommends to move the application to ~/Applications, and allows them to do so via a click on a button.

**Comment by pornel** [comment]
I think you're assuming the authentication dialog is because the app is outside /Applications, but that's not necessarily true. It's quite possible that the app *is* in Applications, but this folder is read-only for the current user (e.g. a machine in an office where IT manages all apps and user is not allowed to), so the suggestion to manually update or move the app could be invalid and misleading. 

Popup of anonymous auth dialog on quit is definitely worrying. Currently we allow customizing it via `SPARKLE_RELAUNCH_TOOL_NAME` config key if you compile Sparkle yourself. We could probably do better here.

We could also automatically ignore the silent update setting if update requires auth, and display the standard "An update is available!" dialog box instead.

**Comment by tfar** [comment]
No. My assumption is that the current user, a non-admin user, installed the app to /Applications, and filled out an authentication dialog in the process. Later on they run the application as non-admin user.

I'm using the latest binary release of Sparkle. Is it possible to adjust the names and the icon used by the dialog without recompiling Sparkle?

**Comment by pornel** [comment]
The name is compiled into the library, so it can't be changed without recompilation. You should be able to swap the icon in `Sparkle.framework/Resources/Autoupdate.app/Contents/Resources/AppIcon.icns`

**Comment by zorgiepoo** [comment]
This sounds like it was a bug; sparkle should not unexpectedly prompt auth dialogs on app termination, nor attempt to do silent updates when an auth dialog is required. Assuming it's fixed in 2.x
