### ISSUE TITLE
"You're Up To Date" (except I'm not!)

### ISSUE THREAD

**Issue by HeadBanging** [sparkle-project/Sparkle#1078]
After a hiatus of several years, I'm using Sparkle again.  I downloaded the latest version, followed the instructions, set up a fresh new XML file on my website (https://www.45rpmsoftware.com/MailRaider/MRAC.xml) and began to test thoroughly.

The problem is that my app always claims to be up to date - even though it isn't.  I'm somewhat perplexed - I used to have this working beautifully, but now it doesn't want to work at all.  

Has anyone else experienced this?  I think I've formatted my XML correctly - but it doesn't appear to be working at all.  There are no clues in the console or the app logs either…

My app is sandboxed - just in case that's causing the problem.  Some docs seem to suggest that Sparkle doesn't like sandboxing, but others seem to imply that sandboxing is fine these days. I can't turn off sandboxing though, because I'm using the same project (albeit a different target) for the App Store…

All help gratefully received.

**Comment by pornel** [comment]
Regarding sandboxing:

 - Sparkle 1.x doesn't support sandboxing. There are some old forks of Sparkle 1.x that were made to work with sandboxing by allowing the host app bypass sandboxing and do whatever it wants, making whole sandbox completely pointless and effectively provide zero security.

- Sparkle 2.x (https://github.com/sparkle-project/Sparkle/tree/ui-separation-and-xpc) supports proper sandboxing with separation of privileges. If you want sandboxing that actually provides some security, that's the one you should use.

But your issue is unlikely to be related to sandboxing. Your appcast probably has a wrong version that doesn't match your plist: https://sparkle-project.org/documentation/publishing/#internal-build-numbers

**Comment by HeadBanging** [comment]
That fixed it! Thank you very much.
