### ISSUE TITLE
Document appcast specification

### ISSUE THREAD

**Issue by iby** [sparkle-project/Sparkle#1102]
Apologies upfront if I missed something somewhere. I want to fully understand the appcast feed format and the absolute minimum it must provide. From looking through the code it seems some things aren't required, other things aren't mentioned in samples. Knowing this from the documentation would be awesome.

**Comment by pornel** [comment]
You've probably seen these:

https://sparkle-project.org/documentation/publishing/
https://sparkle-project.org/documentation/delta-updates/

We don't have a formal spec. There are probably some quirks we should document, e.g. if you don't add an update archive we'll show "information-only" update.

**Comment by ashur** [comment]
While the tutorial-style documentation is helpful, I’d also really appreciate a more formal spec-style reference for all supported properties: what’s required, what’s optional, etc.

**Comment by ianbytchek** [comment]
@pornel yep, read it, it's obviously very useful, but agree 💯 with @ashur – a plain point-by-point reference would be superb.

**Comment by johnwbyrd** [comment]
This is exactly what xsd sheets are for.  The one at at the top of current appcast.xml is a dead link.  A new canonical one should be created and hosted at sparkle.org.

**Comment by johnwbyrd** [comment]
If anyone does this, please take into account winsparkle.org as well, thanks

**Comment by erikInMT** [comment]
I just want to offer a comment related to some trial-and-error work to determine the 'appcast feed format minimum', like that desired by the person who started this thread.

Our organization uses Sparkle for a MacOS product line and as a matter of course, we have to post a 'dummy' appcast in case an eager user tries our Help > Check for Updates command before we've actually released an updated application.

What I've found recently is that even if the appcast XML is valid and well-formed, the app's Check for Updates command dialog will still display the message 'An error occurred in retrieving update information' **if** the appcast doesn't have an `<enclosure>` element with an `url=` and a `sparkle:version` attribute. I was not able to determine for sure if the `sparkle:shortVersionString` attribute was also required, but those are easy to manage so I always use those too.

This base minimum was found mostly by trial and error, as I said, but also by looking into the SUAppcast.m code inside the project -- only one condition seems to trip the _retrieving update information_ message, and the implication is that the `url` attribute value has to be a real, downloadable package, although I could be wrong about that.

**Comment by sfsam** [comment]
Bump.

**Comment by zorgiepoo** [comment]
Someone can try to create a formal spec or xsd on the [website](https://github.com/sparkle-project/sparkle-project.github.io) if they want to. Most details are documented loosely on the website (except for phased group rollouts, maximumSystemVersion, critical updates off the top of my head, currently).

> What I've found recently is that even if the appcast XML is valid and well-formed, the app's Check for Updates command dialog will still display the message 'An error occurred in retrieving update information' if the appcast doesn't have an <enclosure> element with an url= and a sparkle:version attribute. I was not able to determine for sure if the sparkle:shortVersionString attribute was also required, but those are easy to manage so I always use those too.

The enclosure if specified must have a url. A sparkle:version is required and sparkle:shortVersionString is optional. However the sparkle:version in the enclosure is optional because it (and shortVersionString) can be specified as part of the appcast item element. The enclosure is optional, in that case a `<link>` and `sparkle:version` must be specified and the update item is informational-only.

**Comment by johnwbyrd** [comment]
Please make note of, and try to be reasonably compatible with, https://github.com/vslavik/winsparkle/wiki/Appcast-Feeds , which has already made an effort to solve these problems in a Sparkle-friendly way.

**Comment by zorgiepoo** [comment]
The appcast features documentation page was updated recently https://sparkle-project.org/documentation/publishing/

I don't think a formal spec will make things easier to understand. Lots of fields are optional because some other feature set can be used instead (for example, the enclosure and a link / informational update, or which place to specify the sparkle:version).

**Comment by zorgiepoo** [comment]
More 'formal' spec is in the [SUAppcastItem API reference](https://sparkle-project.org/documentation/api-reference/Classes/SUAppcastItem.html) now, in conjunction with the publishing page above.
