### ISSUE TITLE
DSS1 dropped from OpenSSL

### ISSUE THREAD

**Issue by odrobnik** [sparkle-project/Sparkle#1132]
We are generating the appcast zip signatures with OpenSSL. Due to a major update from OpenSSL 1.0.2 to 1.1.0 we lost the ability to generate the signature in DSS1 format.

Questions: 

- Are these signatures for the ZIPs still necessary, or are the app code signing signatures now sufficient?
- if still necessary: Can Sparkle support other digest format?
- or do we have to use an older OpenSSL binary just for generating DSS1 digest signatures?

**Comment by odrobnik** [comment]
We replaced the `-dss1` with `-sha1` in the signing script and Sparkle update still are working. Why is that?

**Comment by pornel** [comment]
I'm not sure. Openssl flags are not documented well. 

If you're signing a simple .app bundle, then try generate_appcast tool. It doesn't use openssl.

**Comment by greenbuffo** [comment]
According to `man EVP_DigestInit`:

> The link between digests and signing algorithms was fixed in OpenSSL 1.0 and later, so now EVP_sha1() can be used with RSA and DSA. The legacy EVP_dss1() was removed in OpenSSL 1.1.0

So I think that means you can use the `-sha1` argument in place of `-dss1` and get the same result.

**Comment by pornel** [comment]
Thanks. Fixed in 0cb0b2f2c7b07b65231528991ac98dc384e51146

**Comment by odrobnik** [comment]
@greenbuffo Thanks for confirming that!

**Comment by tempelmann** [comment]
On my 10.12.6 system, at least, I cannot use the new sha1 argument for the digest creation - openssl gives an error. The older dds1 works, though. Assuming that the change was tested on macOS 10.13 where I guess openssl 1.1 is present, may I suggest to update the "sign_update" script to check the OS version so that it still works with pre-10.13 system, even if it's using the supposedly less-secure dss1 digest there (I don't really care as I will deliver via https anyway).
