### ISSUE TITLE
Where are Sparkle's settings stored?

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1142]
If a user opts to skip a release, where does that get recorded on the system?

**Comment by vadi2** [comment]
This is just for debugging purposes, not for any runtime nefariousness.

**Comment by jkbullard** [comment]
Sparkle stores its settings in the NSUserDefaults for the application in which it is imbedded, that is, the applications "preferences". The preferences for an application are are stored in a .plist file in the /Users/USERNAME/Library/Preferences folder. The name of the file is based on the application's CFBundleIdentifier with the ".plist" appended. So Tunnelblick's file is named "net.tunnelblick.tunnelblick.plist".

That data should never be accessed from the file system because macOS caches it. You must always access it from the keyboard via the [`defaults`](https://ss64.com/osx/defaults.html) command. Programmatic access is via the [`NSUserDefaults class`](https://developer.apple.com/documentation/foundation/nsuserdefaults?language=objc).

The key for the setting concerning skipped versions is "SUSkippedVersion", so if you have skipped a version, the command
     `defaults read XXXXXXX.plist | grep SUSkippedVersion`
should show the version that you skipped.

**Comment by pornel** [comment]
Thanks @jkbullard for great reply.
