### ISSUE TITLE
Auto update check on menu bar application?

### ISSUE THREAD

**Issue by martomi** [sparkle-project/Sparkle#1163]
I'm trying to configure automatic update checker and have the following in Info.plist:

```
SUEnableAutomaticChecks: YES
SUFeedURL: ...
SUScheduledCheckInterval: 3600
SUPublicDSAKeyFile: dsa_pub.pem
```

Yet no matter how much I wait I don't get prompted that a new update is available. The updater works if I manually click the button to "Check for Updates" in the menu.

My guess is that this is cause because I'm developing a menu bar application that relies on a Popover to show content and doesn't have any window that can come in focus? Is there a way to make it work for this use case?

**Comment by jkbullard** [comment]
It probably doesn't have anything to do with being a menu bar application -- Tunnelblick is one and does auto update checking with no problem. (It's complicated code but you can find it at 

You do need to follow the instructions carefully, though, and have the proper code in `applicationWillFinishLaunching:` and `applicationDidFinishLaunching:`.

In Tunnelblick, updating is handled in [MenuController.m](https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/MenuController.m) lines 4070-4090, which invoke setupUpdaterAutomaticChecks (lines 3974 - 4005). But there is other setup done in `applicationDidFinishLaunching:`, and there may be other pieces of code scattered throughout MenuController; search for "updater". (Also, note that Tunnelblick also uses Sparkle to update "configurations"; that's set up separately from the updates.)

**Comment by martomi** [comment]
Thanks for the example! I've read through their implementation. Seems like I need to manually call the `checkForUpdatesInBackground` function in `applicationDidFinishLaunching`. Then it works!

I was hoping that it would get called automatically by Sparkle, because the documentation states:
```
// You do not need to call this. Sparkle calls it automatically according to
// the update schedule.
```
which never happens with a menu bar application. Also I never get prompted for permission to check for updates from Sparkle which is supposed to come automatically on second launch as far as I understood.

**Comment by jkbullard** [comment]
@martomi  - Glad the example helped. If you copy/pasted from Tunnelblick, you might want to strip out some (or a lot) of it and implement it according to the Sparkle documentation.

 1. Tunnelblick uses a patched, older version of Sparkle, so specifics of the handling of some Sparkle settings may be different now.

 2. Sparkle is usually controlled by the user's preferences. However, Tunnelblick has what it calls "forced" preferences, which can only be modified by a computer admin. To make sure that the user can't override any of Tunnelblick's forced preferences, Tunnelblick uses a couple of different techniques:
 * For settings which are the same for all users of Tunnelblick everywhere (for example, "don't send a system profile when checking for updates"), an Info.plist entry is used. (Tunnelblick protects its Info.plist from being modified except by a computer admin, so this secures those settings.)

 * For settings which can be different in different installations of Tunnelblick, either a Sparkle delegate or an updater set... method is used to ensure that the normal user preference will not be used. It's a bit complicated because Sparkle doesn't have a standard, strict hierarchy of what controls a value: sometimes it's the delegate, and if no delegate, the stored setting, sometimes it's the other way around. If I recall correctly, at one time Tunnelblick even patched Sparkle so that it could override the user's preference.

**Comment by zorgiepoo** [comment]
Yes this is supposed to work, you can test `defaults delete bundle-id SULastCheckTime` before launching such a menu bar app. Also see #924 for related potential upcoming changes.
