### ISSUE TITLE
Embedded Sparkle framework integrity checking

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#1191]
I've not been involved in Sparkle development, but as a developer I've used the package for several years in different products. More often than not hackers try to crack and pirate my software, and sometimes I try to find such versions to try and see how the hackers are circumventing my license checks. 

In one such case I found today it appears that they've used the embedded Sparkle framework in the bundle as a way in, which is why I've now submitted this issue. In this case they had hidden their libConfigurer64.dylib code in Sparkle.framework/Versions/A/Resources 

For safety reasons I never ran the cracked application, so I don't know what it would do or how/if it got past the code signing or my other checks. But I'm sure it 'worked' as it was being distributed. And as a lot of developers use embedded sparkle frameworks it's worrying if it's possible to embed third-party code in the framework that can then be used. Perhaps there is some way for Sparkle to check the framework integrity in making sure that no files have been added or modified in it?

Note that in this case it's not an update that has been altered and needs to be checked in an update situation, but rather a compromised bundle that is distributed via other channels. And as the user wants a pirate version they may also disregard system warnings about code-signing failures.

**Comment by kornelski** [comment]
What you're asking for is a DRM. There's nothing Sparkle can do about it. 

In this situation the "attacker" has full control over everything your application does. If Sparkle was verifying its own integrity, then the attacker could replace Sparkle.framework with a version that doesn't.

If you run `otool -L` on your executable you'll find it relies on dozens of libraries, all of which can be patched and replaced. And your main executable can be patched, too.

You could verify integrity of your app's bundle with Apple's Code Signing the same way Sparkle does it when installing updates. You can't use Sparkle's code for it, because Sparkle checks whether old and new identities are the same, but you'd need to check whether existing identity matches *your* specific identity. Of course the attacker can flip one bit in your program changing `if (matches)` to `if (!matches)` to defeat the check, or patch `Security.framework`, etc.

**Comment by lostminds** [comment]
Yeah, I guess it's hard to get around this kind of problem in an air-tight way. I just wanted to let you guys know since it involved the Sparkle framework in this case, and it might affect more applications that use it.

**Comment by digitalmoksha** [comment]
@lostminds Would using the [ui-separation-and-xpc](https://github.com/sparkle-project/Sparkle/tree/ui-separation-and-xpc) help your situation at all?

**Comment by lostminds** [comment]
Perhaps, and thank you for the suggestion. For now though I'll probably stick with the regular version and implement some other checks that at least makes this particular crack not work.

**Comment by digitalmoksha** [comment]
@kornelski any thoughts when a Sparkle 2.0 based on the `ui-separation-and-xpc` branch might be possible? 😄

**Comment by kornelski** [comment]
Sparkle 2.0 doesn't change that at all, and I don't think any of Sparkle ever will. We're not in the DRM business. Sparkle protects against attacks from outside the computer, not from the inside:

https://blogs.msdn.microsoft.com/oldnewthing/20060508-22/?p=31283

"Someone can change a file on their own disk on their own computer" is not our threat model.

No matter what we do in Sparkle — we can check its integrity, run antivirus, do retina scan and ask for your passport — the attacker who cracks an app can always just simply drag Sparkle.framework to the trash, and replace it with their own framework.

Such things are solved by integrity verification *before* any code is ran, but that is technically impossible for Sparkle, and such system is totally out of scope of this project.

**Comment by digitalmoksha** [comment]
@kornelski sorry, I wasn't actually pushing for 2.0 to fix this, it was a little more selfish - I use that branch and was hoping it would become the officially supported one soon 😄 

As always, thank you for your continuing hard work on Sparkle!
