### ISSUE TITLE
Crash on 10.10 when feed xml file is absent

### ISSUE THREAD

**Issue by KosmicTask** [sparkle-project/Sparkle#1199]
On OS X 10.10 SUAppCast -reportError: crashes if the update xml file is not present on the target server.
I suspect that the issue will reside in the completion block called by -reportError: but I wasn't able to confirm this.

Sorry I cannot give more info here but head won't build on 10.10.

**Comment by kornelski** [comment]
Can you post the crash report? Or attach Xcode debugger to the process before it crashes and get more info?

**Comment by mugginsoft** [comment]
Will do.

**Comment by mugginsoft** [comment]
Date/Time:             2018-03-22 17:01:14.716 +0000
OS Version:            Mac OS X 10.10.5 (14F1808)
Report Version:        11
Anonymous UUID:        864C7259-C9D1-1196-6DCB-88994F4C1CE4

Sleep/Wake UUID:       C67BD021-FA37-424D-B1CB-57CC718EA950

Time Awake Since Boot: 11000 seconds

Crashed Thread:        5  Dispatch queue: NSOperationQueue 0x60800083f4c0 :: NSOperation 0x600000652c00 (QOS: LEGACY)

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010

VM Regions Near 0x10:
--> 
    __TEXT                 0000000109d37000-000000010a1e6000 [ 4796K] r-x/rwx SM=COW  /Users/USER/Desktop/MyApp

Application Specific Information:
Performing @selector(_close:) from sender _NSThemeCloseWidget 0x60000018f970
abort() called

Thread 5 Crashed:: Dispatch queue: NSOperationQueue 0x60800083f4c0 :: NSOperation 0x600000652c00 (QOS: LEGACY)
0   libsystem_kernel.dylib        	0x00007fff9084f286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff8d7989ab abort + 129
2   libmonosgen-2.0.1.dylib       	0x000000010b4049bb mono_handle_native_crash + 603
3   libmonosgen-2.0.1.dylib       	0x000000010b355e3a mono_sigsegv_signal_handler + 202
4   libsystem_platform.dylib      	0x00007fff8a2fbf1a _sigtramp + 26
5   org.sparkle-project.Sparkle   	0x000000010a99e498 -[SUAppcast reportError:] + 683
6   org.sparkle-project.Sparkle   	0x000000010a99d039 -[SUAppcast downloaderDidFailWithError:] + 63
7   org.sparkle-project.Sparkle   	0x000000010a9aa5d9 -[SPUDownloaderSession URLSession:task:didCompleteWithError:] + 96
8   com.apple.CFNetwork           	0x00007fff8dd4e509 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke235 + 62
9   com.apple.Foundation          	0x00007fff847e68b8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
10  com.apple.Foundation          	0x00007fff847e6685 -[NSBlockOperation main] + 97
11  com.apple.Foundation          	0x00007fff847e5b3c -[__NSOperationInternal _start:] + 653
12  com.apple.Foundation          	0x00007fff847e5613 __NSOQSchedule_f + 184
13  libdispatch.dylib             	0x00007fff8e194e73 _dispatch_client_callout + 8
14  libdispatch.dylib             	0x00007fff8e1985cd _dispatch_queue_drain + 1100
15  libdispatch.dylib             	0x00007fff8e198030 _dispatch_queue_invoke + 202
16  libdispatch.dylib             	0x00007fff8e197bef _dispatch_root_queue_drain + 463
17  libdispatch.dylib             	0x00007fff8e197a1c _dispatch_worker_thread3 + 91
18  libsystem_pthread.dylib       	0x00007fff8c32da9d _pthread_wqthread + 729
19  libsystem_pthread.dylib       	0x00007fff8c32b3dd start_wqthread + 13

**Comment by mugginsoft** [comment]
Its crashing on startup so attaching Xcode isn't an option without a bit of re engineering.

**Comment by mugginsoft** [comment]
Though a bit of re-engineering isn't out of the question! I would like this sorted as I have to support back to 10.9

**Comment by kornelski** [comment]
I think if you use Xcode to run an app (that uses Sparkle) in debug mode, it will catch it.
