### ISSUE TITLE
Global flag to disable Sparkle updates system-wide

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#130]
I think it'd be useful if the user could set a global default to disable Sparkle across his system:
– an administrator of a lab of machines may want to control their update process tightly
– an app like AppFresh might want to offer to "take over" the update tasks for your system.

**Comment by timsutton** [comment]
Interesting point about access from sandboxed apps in that particular situation. However, both the current-user and any-user global domains seem to contain only preferences for Apple preferences (on a machine I've been migrating with each OS release since 10.6, and using full time since 2010), and Apple [discourages apps](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/UserDefaults/AboutPreferenceDomains/AboutPreferenceDomains.html) from storing their prefs there.

**Comment by zorgiepoo** [comment]
```
defaults write -g SUEnableAutomaticChecks -bool NO
```

It won't affect existing apps that have already ran but will propagate to new apps that haven't ran yet. For existing apps you can change the default on them. Apps can always incorrectly ignore the default but that's on them.

I don't think I want to add a secondary user default flag bound to automatic checking of updates (for UX and maintainability reasons, not that I have something against globally disabling software updates).
