### ISSUE TITLE
When i tap the relunch and install button,app can not update

### ISSUE THREAD

**Issue by crazypoo** [sparkle-project/Sparkle#1338]
[Sparkle] Failed to release quarantine on /Users/dengjiehao/Library/Containers/com.crazykidhao.CloudGateBackground/Data/Library/Caches/com.crazykidhao.CloudGateBackground/org.sparkle-project.Sparkle/好厉害的App (Autoupdate).app with error Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Failed to remove file quarantine on 好厉害的App (Autoupdate).app.}

**Comment by kornelski** [comment]
Thanks for the report.

This message is not an error. It's only a warning. Sparkle continues in that situation as normal.

**Comment by PascalHarris** [comment]
I'm having the same problem (on Mojave) - when (during test) I try to update my app to the latest version I get 

Failed to release quarantine on /Users/pascalharris/Library/Containers/com.45RPMSoftware.MailRaider-Pro-OAS/Data/Library/Caches/com.45RPMSoftware.MailRaider-Pro-OAS/org.sparkle-project.Sparkle/Autoupdate.app with error Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Failed to remove file quarantine on Autoupdate.app.}

In my case at least, this is an error because the app update never completes.  What to do?

**Comment by kornelski** [comment]
This message is not an error. It's only a warning. Sparkle continues in that situation as normal.

If the update fails, then it fails for a different reason, not this one.
