### ISSUE TITLE
Migrating from DSA to EdDSA

### ISSUE THREAD

**Issue by gnachman** [sparkle-project/Sparkle#1355]
I'm trying to stop using DSA keys in favor of EdDSA. I'd like to minimize the amount of time that DSA keys are trusted. I have plenty of users in the field with old builds (using Sparkle 1.7.0).

It seems I cannot change the DSA key. If I change it, updates fail saying "DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the new public key shipped with the update doesn't match the signature. The update will be rejected."

I cannot remove the DSA key. Doing so causes the update to fail with "A public DSA key is found in the old bundle but no public DSA key is found in the new update. For security reasons, the update will be rejected."

From this I conclude the migration path is to support both keys for time (perhaps as little as one version). I will need to keep the one of these releases in the appcast indefinitely.

Then I need to provide a way for users running this release with both keys to upgrade to the EdDSA-only version without letting users on the DSA-only releases know about it (lest they try to upgrade and get one of the aformentioned errors). I guess this means I need to use a different URL for appcasts for my Sparkle 1.21 users.

Is this correct?

**Comment by kornelski** [comment]
I haven't put out much thought into migration path off it yet, so Sparkle is cautious and conservative about the new keys.

I think the best solution would be to change Sparkle itself to start ignoring old DSA completely.

**Comment by gnachman** [comment]
I've tested using the plan I suggested and it works, but it is a pain. If you relax the requirement that an app with a DSA public key requires a DSA signature then it could get you down to two appcasts. I don't know the reasoning behind that decision, though. Is that to protect developers from their own mistakes or is there a specific vulnerability you were worried about?

**Comment by kornelski** [comment]
There's no vulnerability per se. I've just been (too) careful not to create a logic bug.

For example, adding EdDSA signature and EdDSA key to the *new* app shouldn't be enough to pass EdDSA signature verification, because both signature and the key are new and therefore untrusted in this scenario. The app needs to check new signature against the old key to ensure the chain of trust is unbroken.

Technically there's no problem at all doing that. It's just that adding EdDSA already required many changes in the signature verification code, and supporting all of the combinations separately, securely and with helpful error handling, adds a ton of new code paths: {no DSA, old DSA, old EdDSA, old DSA + EdDSA} * {new DSA, new EdDSA, new DSA + EdDSA} * {app code signing, unsigned bundle, package}.

**Comment by zorgiepoo** [comment]
We should lax the requirement on DSA when EdDSA is provided.

However, in the present state, for many developers that use Apple Code Signing and app bundle updates, if the Apple code signing signatures match from the old/new apps (eg both are Dev ID signed), this will allow rotation of dropping DSA in a new update.

**Comment by zorgiepoo** [comment]
The requirement has been relaxed and we have website documentation on migration now.
