### ISSUE TITLE
Xamarin.Mac compatibility on latest unified Mono APIs

### ISSUE THREAD

**Issue by Matthius** [sparkle-project/Sparkle#1361]
Hello,

I have migrated an old mono project to a Xamarin.Mac project that uses the last unified Mono API (to be able to compile in 64 bit), and after seeing that my old Sparkle bindings failed to compile because they were using an old Mono API (32 bit), I wanted to create a new binding project and link your latest version of Sparkle.

But it does not work. It says the XamMac is not compatible with my project (the project compiles, but I can't link it to my main project).
If I force the use of the latest unified Xamarin.Mac, the native project fails to compile.

So do you guys know if it is even possible to link this framework to the latest Mono APIs?
I have tried the bindings of this (awesome) guy: https://github.com/rainycape/SparkleSharp
But I have the same issues.

Hope you guys can help me!

**Comment by kornelski** [comment]
We generally support only Cocoa. Stuff will break in subtle ways you don't have Cocoa's main runloop running.

I can't help you with non-Xcode integration.

**Comment by Matthius** [comment]
But rainycape did it with an older version. You say it is not possible with the current one?
Xcode is used by Visual Studio for Mac (Xamarin). There are some obj-c bindings in the code. It's just that the classes seem to not be compatible with the 64 bits mono.

**Comment by kornelski** [comment]
Nothing has changed in terms of compatibility. If you were able to make older version work, then the latest 1.x will work, too.

I'll just reiterate that you *must* set up a Cocoa runloop, as otherwise timers and networking code will malfunction in Sparkle. 

Usually apps built with other frameworks don't run `NSApplicationMain` that sets up the environment necessary for Sparkle to run, so you need to create a main thread and event loop for Cocoa "the hard way". I know almost nothing about Xamarin, so I can't help you with this.

**Comment by Matthius** [comment]
It is in a cocoa runloop I guess, it is using the NSApplicationMain. That might be why it worked with the old mono version.
Also it won't work now because mono changed their lib and when I try to bind yours it is using an old version of mono.

I think I have to find another way of linking it...
