### ISSUE TITLE
Sparkle not logging w. 1.21.3

### ISSUE THREAD

**Issue by hstriepe** [sparkle-project/Sparkle#1463]
I do not see entries in the Sparkle logs for our app running 1.21.3. This is independent of working ok or running errors. It makes trouble shooting the latter a real challenge.

The only entry I see is running 1.5(beta) way back beginning of Aug.

The apps are not sandboxed.

**Comment by kornelski** [comment]
Are you looking at the logs in Console.app?

**Comment by hstriepe** [comment]
Both console app and directly. They look the same.

**Comment by hstriepe** [comment]
I should note I see this issue on two systems and both in Mojave and Catalina B7.
Our apps are not sandboxed but notarized. Neither should really make diff for logging.

**Comment by kornelski** [comment]
This 1.5(beta) is very surprising, because that is very very old, and 1.5 used to log to a custom text file, in a custom Sparkle folder. Current Sparkle doesn't use any of this. It doesn't write to a text file, and it doesn't create a custom Sparkle folder.

So if you're seeing logs from 1.5 anywhere, you either have wrong version of the framework installed somehow, or looking at a compleeeeetly wrong file.

**Comment by hstriepe** [comment]
It's is a DropCopy app log. Not a smidgeon anywhere else in Console.
