### ISSUE TITLE
CI/CD with Github actions

### ISSUE THREAD

**Issue by crewshin** [sparkle-project/Sparkle#1529]
I'm looking for a little help from someone with a little more sparkle experience than I do. I'd like to build out a github action for building and deploying a macOS app to S3. I'm a little hung up on how to achieve the `generate_appcast` aspect of it from within what is almost certainly a container.

If anyone has a little free time to help... I'll reward with a free write-up/tutorial for the community. Possibly a cold beer if you live close to me :)

**Comment by crewshin** [comment]
After doing a little more research, I'm not exactly sure how I can get around the signing aspect without trying to rebuild it from a github secret. Unless I can issue updates without signing?

**Comment by kornelski** [comment]
`generate_appcast` can take the private key as an argument now. You would have to have the key in the CI. 

It would be risky on public CI, and you'd have to be careful not to allow pull requests with that config, since a malicious PR could steal the key.

Sparkle supports updates signed with only Apple Developer ID if you never configure any DSA signing in the app, but in such case you're locked into that ID forever and there's no way to authorize an update in case your Apple ID ever changes.

**Comment by MMavrisPaleBlue** [comment]
@crewshin Did you manage to run it on CI/CD?
