### ISSUE TITLE
Generate-Keys Tool: Add “Export Key” capability

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#1535]
I do not want my private Sparkle keys in my Keychain. Reasons:

1) I keep all encryption keys for each app I develop in a specific location so that they get backed up correctly to my remote servers.

2) I use separate keys for each app I develop and cannot do that with the new ed25519 keys because Sparkle assumes I use a single key for everything.

3) I do not mix my personal Keychain items with my development Keychain items.

I see that the new `sign-update` tool accepts an `-s` flag that allows me to provide a private key. However, I cannot find a way to properly export the private key from Keychain Access and I'm not sure what format an ed25519 key should have as a file on disk.

Please modify the `generate-keys` script to (optionally) output a private key file instead of assuming that the Keychain is appropriate.

**Comment by kornelski** [comment]
Sparkle's integration with the Keychain is not pretty. It's partly because Keychain doesn't support curve 25519 "natively" and the key has to be smuggled in as a "password". 

To export the key, find Sparkle's "password" in the Keychain and copy that. 

Storing keys on disk is scary. Any malware could just grab them. I think switch to Keychain has been a significant security improvement. It's also a usability improvement, because you don't have to manage files. You don't have to pass path to the private key to commands. You can't mix up public and private keys, because you don't handle the private part.

I'm taking inspiration from Developer ID here. It's supposed to be shared between apps, and Xcode puts your Developer ID certificates in your login keychain. 

I could make Sparkle support multiple keychain entries, but signing is already PITA and I didn't want to add more failure points to the system.

Would it suffice if `generate_keys` had an export option?

**Comment by bdkjones** [comment]
Yep, an export option would definitely suffice. I saw the "password" in the keychain, but in my experience private keys generally have a definite format, such as: 

     -----BEGIN RSA PRIVATE KEY-----
     gobbeldygook
     -----END RSA PRIVATE KEY-----

I wasn't sure if just that password string in a file would be sufficient, or if 25519 keys need specific formatting.

**Comment by kornelski** [comment]
25519 private keys are 128-bit, so they don't need the whole ceremony and custom file formats that KB-large RSA keys needed.

**Comment by zorgiepoo** [comment]
There's an option to export/import keys in `generate_keys` on top of master / 2.x now.

**Comment by manishjain999** [comment]
what is the command to export keys using terminal ?

**Comment by zorgiepoo** [comment]
Check `generate_keys --help`
