### ISSUE TITLE
Question: Intiate a update without appcast, in a programmatically

### ISSUE THREAD

**Issue by supercharger** [sparkle-project/Sparkle#155]
I want to initiate a update without a update without a appcast.
I meant, Application  decides on the update and the retrieves the URL  of the download.

In this case, once application will initiate the update to sparkle.
Sparkle will take care of the download, and update and restart.

Is there any support in the sparkle ?
If not can this be treated as feature request.

**Comment by suy** [comment]
Hi.

This issue was closed without comment. Is not intended at all to provide a public interface to do this, or there is already one that I've overlooked?

I think it would be nice to have it, because then it will be easier to have custom logic in the UI (e.g. mandatory updates like in #76, or just integrate the buttons in a larger/different UI without dialogs like in #521), or a complete custom file format (e.g. JSON like in #427).

My use case is that I have an application written with Qt in C++. Adding the network code to poll for updates, parse JSON, and show a message to trigger the download is easy. But leveraging Sparkle's nice battle tested code for doing the upgrade and restart of the application is a lot better than doing it again. So I don't see how can I bridge the two worlds.

The [documentation on customization](http://sparkle-project.org/documentation/customization/) mentions looking at the driver implementation for deeper customization, but as I understand it, this requires modification of Sparkle itself, not usage of the API, right?

Thanks, and sorry if I derailed a bit into a question, but I don't know other channel for discussing this.

**Comment by jakepetroules** [comment]
So basically you want to use Sparkle, but with a custom UI?

**Comment by suy** [comment]
More or less, yes. I would like to tell Sparkle to install an already downloaded file. Or if Sparkle needs to download the file for whatever reason, point it to an URL where it is. I have nothing against XML or Cocoa. :-)  Is just that is easier for me to do as much as possible with Qt, and the application is already using JSON for everything (so the server side people might prefer it). As per #76 and my understanding of the code, it seems I can't disable the "skip this upgrade" option either. I could work around it this way too.

**Comment by pornel** [comment]
It'd be nice to support custom UIs better, and for that we need to decouple Sparkle's UI and logic better (#521).

Sparkle already has a bunch of hairy logic to handle timing of polling and deferring of updates. Do you really *need* to rewrite that?

For the appcast you don't even need XML tools on the server: you can host it as a static text file or generate it with any text/html templating language. 

Serialisation isn't the hard part. You still need to provide versions, tags, download links, DSA signatures, but to use `{}` instead of `<>` you'd need to reinvent a lot of boring glue code.

**Comment by suy** [comment]
On Monday, November 30, 2015 7:34:47 PM CEST, Kornel wrote:
> Sparkle already has a bunch of hairy logic to handle timing of 
> polling and deferring of updates. Do you really need to rewrite 
> that?

My requirements about asking the server and comparing the version make it pretty trivial to implement, and I did it very quickly in a cross-platform way. To me, the code that does the upgrade is the really valuable. Just extracting the contents of a DMG reliably is difficult. Add the magic that you have about the quarantine, timestamps, etc.

> For the appcast you don't even need XML tools on the server: 
> you can host it as a static text file or generate it with any 
> text/html templating language.
>
> Serialisation isn't the hard part. You still need to provide 
> versions, tags, download links, DSA signatures, but to use {} 
> instead of <> you'd need to reinvent a lot of boring glue code.

I don't care about XML or JSON (actually I prefer XML for hand written things, as this probably would be). But the application is already using a JSON API for everything, and I don't have anything to say about the server side. And right now the JSON is almost literally this:

    {"appurlmac":"http://static.example.com/App-0.9.8.dmg",
     "appurlwindows": "http://static.example.com/app-0.9.8.msi",
     "appversion":"0.9.8"}

But well, this is just my 2 cents about what I think it would be nice to have, not only for my use case, because I think other issues could have a programmatically initiated upgrade as a workaround for other limitations. You do the work, so you are free to do as you please of course. :)

**Comment by ezekg** [comment]
I know this is an old issue, but is there any interest in continuing the conversation here around supporting programmatic updates without having to generate and use an `appcast.xml`?

What if Sparkle also allowed an update server to respond with an HTTP `301`, `302`, `303` or `307` redirect pointing to the new release file's URL? This would bypass the XML file and allow for third-party distribution services, such as [my own](https://keygen.sh/docs/api/#releases-actions-upgrade-by-version), to be more easily integrated with Sparkle, without the third-party service needing to add a compatibility layer (i.e. generating a dynamic per-license `appcast.xml` endpoint, pointing to the authenticated update URLs.)

What do you all think? I'm not a Sparkle expert by any means, so let me know if this isn't feasible — I know Sparkle does a lot of work with signature verification and things like that, so supplying a redirect straight to the update file's URL would not include things like release name, release notes, EdDSA signatures, etc. that the XML supports.

p.s. I'd love to sponsor/donate to Sparkle on behalf of Keygen, given we could add some sort of HTTP redirect support like this. Let me know if you provide options for that. 🙂

**Comment by kornelski** [comment]
Programmatic updates are supported by having the server generate and dynamically return XML of the appcast. Technically that's just like generating an HTML page with a download link. You can use any server-side framework. The appcast itself isn't signed, and doesn't require any tooling. If you want, you can just concatenate a bunch of strings.

**Comment by ezekg** [comment]
@kornelski no worries — just figured I'd bring it up. I was trying to avoid adding a Sparkle-specific compatibility endpoint that returns a dynamic `appcast.xml` payload, but I understand if what I proposed doesn't mesh well with the project's vision. 

Appreciate your time. 👍
