### ISSUE TITLE
Setting SUDefaultsDomain does not work

### ISSUE THREAD

**Issue by spearway** [sparkle-project/Sparkle#1615]
if you set SUDefaultsDomain for a sandboxed app it does not work:

2020-06-16 15:29:19.079038-0700 Alchemy[18856:2647650] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x600002c05c00> (Domain: 5Q6TG8SL97.Alchemy, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

**Comment by spearway** [comment]
Sorry wrong label should be 2.x

**Comment by zgerrard** [comment]
Hi, did you solve this issue? I am also facing the same problem.

**Comment by malikusha** [comment]
> Hi, did you solve this issue? I am also facing the same problem.

Same

**Comment by zorgiepoo** [comment]
This is due to trying to a different defaults domain.
https://developer.apple.com/documentation/foundation/nsuserdefaults?language=objc "Sandbox Considerations"

I thought their might be a [temporary entitlement exception](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html) around this, but I'm not so sure there is.

**Comment by zorgiepoo** [comment]
"Shared Preference Domain Temporary Exceptions" in https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html
