### ISSUE TITLE
Installer doesn't seem to complete

### ISSUE THREAD

**Issue by pparekh7** [sparkle-project/Sparkle#1650]
### Description of the problem

When updating my app, I am able to download the pkg.zip successfully. When I select "Install and Relaunch" and enter my login credentials, the installer starts but doesn't seem to finish leaving fileop waiting and in turn Autoupdate waiting.

This seems to be happening on Mac OS 10.14.6 having all security updates applied. It doesn't seem to happen if the latest security update is not applied to 10.14.6. It is not reproducible on Catalina.

The filepath that's supplied to the installer has spaces in it so I changed it to have quotes but that doesn't seem to help.

If I run with the same parameters to installer from the terminal, it runs fine.

### Do you use Sandboxing in your app?

No

### Version of `Sparkle.framework` in the latest version of your app

1.20.0

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

1.20.0

### Sparkle's output from Console.app
```

```

### Steps to reproduce the behavior

My app is called iLok License Manager and the latest version is available at https://www.ilok.com
I can supply a link to an older version as needed.

**Comment by pparekh7** [comment]
Just to clarify: We've been using Sparkle for a couple of years now so this is a new issue that's not related to packaging/appcast etc.
Is anyone else running into this? 
At this point, I don't know if an Apple bug or a Sparkle issue. I would appreciate some help on resolving this.

Thanks!

**Comment by catlan** [comment]
I noticed that same issue. I did upgrade to sparkle 1.20.0 just the previous, so it is possible that this is a regression. But I'm more likely to think it is related to macOS 10.14.6.

Attached [Sample of installer.txt](https://github.com/sparkle-project/Sparkle/files/5339260/Sample.of.installer.txt)

**Comment by pparekh7** [comment]
I've reported this to Apple too since its a bit unclear where the problem lies.

**Comment by jcredland** [comment]
Hey, we have a similar, possibly the same, problem with our Loopcloud application on one of our staff computers.  Suddenly we are getting a hang in the auto update app, the installer runs but the app doesn't seem to know about it. 

Again - OSX 10.14.6.

Stack trace of hung app is:

```
Call graph:
    2787 Thread_8060156   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2787 start  (in Autoupdate) + 52  [0x10d69ede4]
    +   2787 main  (in Autoupdate) + 683  [0x10d6a046a]
    +     2787 -[NSApplication run]  (in AppKit) + 699  [0x7fff46329588]
    +       2787 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]  (in AppKit) + 1361  [0x7fff4632f46b]
    +         2787 _DPSNextEvent  (in AppKit) + 1135  [0x7fff4633077d]
    +           2787 _BlockUntilNextEventMatchingListInModeWithFilter  (in HIToolbox) + 64  [0x7fff47f98c76]
    +             2787 ReceiveNextEventCommon  (in HIToolbox) + 603  [0x7fff47f98ee5]
    +               2787 RunCurrentEventLoopInMode  (in HIToolbox) + 292  [0x7fff47f991ab]
    +                 2787 CFRunLoopRunSpecific  (in CoreFoundation) + 455  [0x7fff48d3a552]
    +                   2787 __CFRunLoopRun  (in CoreFoundation) + 1612  [0x7fff48d3adf0]
    +                     2787 __CFRunLoopServiceMachPort  (in CoreFoundation) + 328  [0x7fff48d3b882]
    +                       2787 mach_msg  (in libsystem_kernel.dylib) + 60  [0x7fff74e13768]
    +                         2787 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fff74e1321a]
    2787 Thread_8060171   DispatchQueue_10: com.apple.root.default-qos  (concurrent)
    + 2787 start_wqthread  (in libsystem_pthread.dylib) + 13  [0x7fff74ed13fd]
    +   2787 _pthread_wqthread  (in libsystem_pthread.dylib) + 583  [0x7fff74ed16b3]
    +     2787 _dispatch_worker_thread2  (in libdispatch.dylib) + 90  [0x7fff74c9fb46]
    +       2787 _dispatch_root_queue_drain  (in libdispatch.dylib) + 324  [0x7fff74c9f3bc]
    +         2787 _dispatch_queue_override_invoke  (in libdispatch.dylib) + 763  [0x7fff74c93a53]
    +           2787 _dispatch_client_callout  (in libdispatch.dylib) + 8  [0x7fff74c9163d]
    +             2787 _dispatch_call_block_and_release  (in libdispatch.dylib) + 12  [0x7fff74c905f8]
    +               2787 __23-[AppInstaller install]_block_invoke  (in Autoupdate) + 176  [0x10d69f87c]
    +                 2787 -[SUGuidedPackageInstaller performFinalInstallationProgressBlock:error:]  (in Autoupdate) + 207  [0x10d6a7c6a]
    +                   2787 -[SUFileManager executePackageAtURL:progressBlock:error:]  (in Autoupdate) + 352  [0x10d6a7629]
    +                     2787 -[SUFileManager _authorizeAndExecuteCommand:sourcePath:destinationPath:lineCallback:error:]  (in Autoupdate) + 1086  [0x10d6a1987]
    +                       2787 __wait4  (in libsystem_kernel.dylib) + 10  [0x7fff74e18352]
    2787 Thread_8060198: com.apple.NSEventThread
    + 2787 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff74ed140d]
    +   2787 _pthread_start  (in libsystem_pthread.dylib) + 66  [0x7fff74ed5249]
    +     2787 _pthread_body  (in libsystem_pthread.dylib) + 126  [0x7fff74ed22eb]
    +       2787 _NSEventThread  (in AppKit) + 175  [0x7fff463384a2]
    +         2787 CFRunLoopRunSpecific  (in CoreFoundation) + 455  [0x7fff48d3a552]
    +           2787 __CFRunLoopRun  (in CoreFoundation) + 1612  [0x7fff48d3adf0]
    +             2787 __CFRunLoopServiceMachPort  (in CoreFoundation) + 328  [0x7fff48d3b882]
    +               2787 mach_msg  (in libsystem_kernel.dylib) + 60  [0x7fff74e13768]
    +                 2787 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fff74e1321a]
    2787 Thread_8065205
      2787 start_wqthread  (in libsystem_pthread.dylib) + 13  [0x7fff74ed13fd]
        2787 _pthread_wqthread  (in libsystem_pthread.dylib) + 458  [0x7fff74ed1636]
          2787 __workq_kernreturn  (in libsystem_kernel.dylib) + 10  [0x7fff74e14bfa]
```

I'd be interested if you or anyone else has any insight or suggested debugging steps for this.

Looks like we are on 1.22.0 for all relevant versions of the app.

**Comment by jsiegers** [comment]
Same problem here for our users.
We're seeing this only on 10.14.6 with installing a pkg file. The whole machine will stall for about 3 minutes and then continue. Console would say something like this during this time:

`efault	11:06:18.363709 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/PlugIns, NSUnderlyingError=0x7f82252200f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:06:18.366810 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/PlugIns, NSUnderlyingError=0x7f8225219e90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:06:18.411945 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/PlugIns, NSUnderlyingError=0x7ff5d44920d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:06:18.451307 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/PlugIns, NSUnderlyingError=0x7f822532fde0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:06:18.455466 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/PlugIns, NSUnderlyingError=0x7f8225226b70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:08:38.253684 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/PlugIns, NSUnderlyingError=0x7ff5d683b490 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:08:38.314560 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/PlugIns, NSUnderlyingError=0x7ff5c4422ed0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:08:38.318531 -0400	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file "PlugIns" couldn't be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Postlab.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/, NSFilePath=/Applications/Postlab.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/PlugIns, NSUnderlyingError=0x7ff5d682fd40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

And finally:

`11:28:50.554828 -0400	Autoupdate	default	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 434 vs 492, 512, <private>`

**Comment by jsiegers** [comment]
Also to clarify. I think it might be related to installing pkgs through the AutoUpdate app.
The AutoUpdate app also doesn't quit. It just hangs. After the system has come back to live you'll need to manually quit the AutoUpdate app. When you startup the real application you can see that it has indeed been updated. 
Installing the pkg the normal way works fine.

**Comment by catlan** [comment]
@pparekh7 Did you report the issue to Apple as bug report or via DTS?

**Comment by catlan** [comment]
Here the answer from Apple Developer Technical Support:

> It appears that you’ve identified a bug report issue under macOS 10.14.6 (when Security update is applied - as per the github posting). However, the issue appears to have been fixed with 10.14.7 [sic].

I requested more information if 10.14.7 is an update in the pipeline or just the 10.14.6 Supplemental Update from October 1, 2020.

With the confirmation that the issue is a system bug, I suggest to close this case. Maybe opening a new feature request allowing sparkle feed to exclude a OS version would make sense.

**Comment by pparekh7** [comment]
I reported it to Apple via their Feedback Assistant tool. I tested it with the last patch that they released for Mac OS Mojave and the issue was not fixed.

**Comment by catlan** [comment]
@pparekh7 Could you provide us the Feedback ID.

**Comment by pparekh7** [comment]
Sure. It's FB8696893.

**Comment by catlan** [comment]
10.14.6 Security Update 2020-007[2] (18G7016) seems to fix the issue. I did not hear back from DTS.

**Comment by pparekh7** [comment]
Yes, I verified that this security update does fix the problem. I'm closing this issue.
