### ISSUE TITLE
Installation fails in non-sandboxed app with 2.x branch

### ISSUE THREAD

**Issue by armadsen** [sparkle-project/Sparkle#1658]
### Description of the problem

I'm trying to troubleshoot a problem, and in order to do so, started by disabling sandboxing and removing the XPC services to run Sparkle 2.x in non-sandboxed/non-XPC mode. Everything proceeds OK until it's time to start the installation. The update fails either with a generic error or silently.

I've done a little debugging, and while the Sparkle XPC architecture is new to me, it seems like the problem likely lies in `SUInstallerConnection`. Specifically, its implementation of `-handleMessageWithIdentifier:data:` calls through to the `self.connection.remoteObjectProxy`. However, in the presumably intended to be non-sandbox/XPC `SUInstallerConnection`, the `connection` property is nil, so this fails. Further, it appears that the invalidation handler for the connection created in `-[SUInstallerConnection setServiceName:hostPath:installationType:]`.  I'm not sure how this is supposed to work, but this seems wrong?

Oh, I should probably mention that I'm using the old `SUUpdater` API for now. I haven't changed any of my client code since switching over from my old fork, which was API compatible with Sparkle 1.x. (I'm not sure I've changed anything significant about my client code since I first integrated Sparkle in 2006.)

### Do you use Sandboxing in your app?

No.

### Version of `Sparkle.framework` in the latest version of your app

2.x (commit 852d678585).

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

Very old custom fork with sandboxing support (probably 2012/2013 era?)

### Sparkle's output from Console.app
```
error	17:07:33.456322-0600	<MyApp>	Error: An error occurred while running the updater. Please try again later. The remote port connection was invalidated from the updater (URL (null))
```

### Steps to reproduce the behavior

1. Use the 2.x branch in an app with sandboxing disabled. Do not include the XPC services.
2. Check for an update making sure the appcast includes a valid update.
3. Choose to install the available update.
4. Note that the install fails with a generic error.

**Comment by zorgiepoo** [comment]
Some confusion here from your troubleshooting. XPC is an IPC mechanism. XPC Services are helper bundles included in an app ran out of process with privilege separation (which Sandboxing happens to require). XPC is the IPC mechanism 2.x uses to communicate to the installer agent/daemon, even if your application is not using XPC Services. This is what you're seeing.

Don't know offhand why connection to the installer fails. Maybe make sure the installer (Autoupdate) is not failing to be launched. Can say that it works on my end (I gave it a test in one of my apps using the older SUUpdater API where I don't use the xpc services). That `SUInstallerConnection` is used sounds correct. If you had the `InstallerConnection` XPC service present for sandboxing an app, it would use `SUXPCInstallerConnection` instead due to privileges required to communicate to installer agent/daemon.

**Comment by armadsen** [comment]
I've fixed the issue I had with the sandboxed/IPC version, so there's not much call to track this down now, especially if you can't reproduce it. I've also switched to the modern API away from SUUpdater. The sandboxed version is working fine. Thank you!

**Comment by zgerrard** [comment]
@armadsen I am encountering the same problem. Please could you explain how you fixed it?

**Comment by zorgiepoo** [comment]
Check Console logs for the installer utility, `Autoupdate`, which aborted early or the process never spawned. Also if you are using sandboxing, refer to Testing bit in https://sparkle-project.org/documentation/sandboxing/
