### ISSUE TITLE
SUAppcastDriver and its delegate...

### ISSUE THREAD

**Issue by mirkoevo** [sparkle-project/Sparkle#1698]
Hi,

from the sources, if the delegate -bestValidUpdateInAppcast:forUpdater: returns nil, it falls back to the standard process.
Is there a reason for this? In my opinion, if the delegate does not return a value, it should abort.

I have noticed that SUAppcastDriver header is not public, but its class methods could be useful for the delegate.

**Comment by billymeltdown** [comment]
> Is there a reason for this? In my opinion, if the delegate does not return a value, it should abort.

In my case I use it to allow beta builds to check for a higher build number even when they have the same public/display version number. In other words, version 1.2.3 beta build 123 should offer to update if 1.2.3 build 124 is available. But otherwise, I want Sparkle's standard version comparison on the public display version number. If this method aborted instead of returning nil that would be impossible, and be a bit undesirable in my opinion. 

Here's an example implementation of what I mean:

```obj-c
- (SUAppcastItem *)bestValidUpdateInAppcast:(SUAppcast *)appcast forUpdater:(SUUpdater *)updater {
    /*
     Here we have an opportunity to provide additional update checking criteria, like considering
     a higher build number for the current version. If we return nil, normal operation should
     proceed for higher version checking.
     */
    SUAppcastItem *item = nil;
#ifdef ENABLE_BETA
    // Get our current build number
    NSInteger currentBuildVersion = [[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleVersion"] integerValue];
    for (SUAppcastItem *candidate in appcast.items) {
        NSInteger appcastBuildVersion = [candidate.versionString integerValue];
        if (appcastBuildVersion > currentBuildVersion) {
            item = candidate;
            break;
        }
    }
#endif
    return item;
}
```

**Comment by zorgiepoo** [comment]
Rule of thumb at least for Sparkle is that all delegate methods (which are all optional) should have a way to fall back to standard behavior as if you didn't implement the method, which allows it to be fully composed. A fundamental example in the framework where this must work is that SUUpdater stub is the delegate of a SPUUpdater, and must implement this method, but whatever is the delegate of SUUpdater may not implement it, etc.
