### ISSUE TITLE
dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle

### ISSUE THREAD

**Issue by Raj-7799** [sparkle-project/Sparkle#1699]
### Description of the problem
I am trying to link the framework with my go executable bundled in a MacOS application. I am using sparkle `1.24.0`. To link the framework with go I am using CGO and passing the following flags for linking the framework : 
```
#cgo CFLAGS: -I ${SRCDIR}/Sparkle.framework
#cgo LDFLAGS: -F ${SRCDIR} -framework Sparkle
```
The link created is as follows : 
```
        @rpath/Sparkle.framework/Versions/A/Sparkle (compatibility version 1.6.0, current version 1.24.0)
```
My app follows the standard structure :
```
Contents
    ├── Frameworks
    │   └── Sparkle.framework
    ├── Info.plist
    ├── MacOS
    │   └── go_executable
    ├── README
    └── Resources
        └── icon.icns
``` 
Although whenever I start the app it shows the following output : 
```
dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: <just path to my executable>
  Reason: image not found
[1]    1834 abort      ./go_executable
```
Load command : 
```
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @rpath/Sparkle.framework/Versions/A/Sparkle (offset 24)
   time stamp 2 Thu Jan  1 05:30:02 1970
      current version 1.24.0
compatibility version 1.6.0
```

Can you please advise what could be the issue?

### Do you use Sandboxing in your app?
No
### Version of `Sparkle.framework` in the latest version of your app
`1.24.0`
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

**Comment by kornelski** [comment]
The rpath should have been `@rpath/../Frameworks/Sparkle.framework/Versions/A/Sparkle`

**Comment by MaddTheSane** [comment]
`rpath` should have at least one `@executable_path/../Frameworks/` entry.

**Comment by kornelski** [comment]
Oh, hi @MaddTheSane!

**Comment by Raj-7799** [comment]
Adding entry into `rpath `worked. Thank you guys 🙌

**Comment by Sam-Spencer** [comment]
I know this issue is closed, but I thought I'd throw in the solution that worked for me (for future viewers).

The issue for me was actually that my app's `Signing Certificate` parameter was set to `Sign to Run Locally`. Which, for some reason doesn't play nice with the Sparkle framework. Instead, I changed it to `Development` and everything worked out (after following the provided setup instructions for Sparkle, of course)!

This [blog post explains it](https://posts.boy.sh/fix-mapped-file-has-no-team-id-xcode).
