### ISSUE TITLE
Docs are incomplete on how to generate keys/appcasts and sign updates if using SPM

### ISSUE THREAD

**Issue by AngeloStavrow** [sparkle-project/Sparkle#1701]
**Context:** This is the first time I've tried integrating Sparkle into a Mac app, and frankly the first time I've tried to _ship_ a Mac app. I've spent a few days now digging through GitHub issues in this repo and other OSS Mac apps, as well as the wider web looking for guidance on this. Very happy to open a PR to update the docs if y'all can point me in the right direction here! 🙂 

I'm trying to work through the [Basic Setup doc][1] for a SwiftUI-lifecycle app and I'm stuck on step 3, specifically:

> First, run `./bin/generate_keys` tool (from the Sparkle distribution root).

Since I added Sparkle via Swift Package Manager in Xcode, I don't have a Sparkle distribution root (that I can find, anyhow). I then downloaded and unzipped the `Sparkle-for-Swift-Package-Manager.zip` archive, and when I try running `./bin/generate_keys` from there, I get this Gatekeeper alert:

<img width="372" alt="generate_keys-Gatekeeper" src="https://user-images.githubusercontent.com/387655/103228052-eae90e80-48fd-11eb-8770-842ddc3c2027.png">

Clearly I'm missing a step here! Any guidance you all can provide would be very helpful and much appreciated.

[1]: https://sparkle-project.org/documentation/

**Comment by kornelski** [comment]
Ehhhh, that looks like yet another code signing problem. 

You can force it through by right-clicking on the executable and selecting "Open" from the menu (you only need to do it once)

**Comment by thebluepotato** [comment]
@AngeloStavrow The files are available in Xcode when you add Sparkle as a SPM dependency, but they are "hidden". Once Xcode has downloaded the Package, you should be able to find all the binaries (and debug symbols) by clicking `Show in Finder` from the context menu relating to the Package (in File navigator). This should open the directory where the package was downloaded and should include all binaries.

**Comment by AngeloStavrow** [comment]
> You can force it through by right-clicking on the executable and selecting "Open" from the menu (you only need to do it once)

@kornelski This worked like a charm for the `generate_keys` tool, thanks!

> This should open the directory where the package was downloaded and should include all binaries.

Thanks for this, @thebluepotato! I can confirm that this gets me to the Sparkle repo that Xcode downloads, but the only thing in `/bin` is `/old_dsa_scripts` — so I think I still need to get/build the tools, unless I'm looking in the wrong place? Sorry for this, I'm feeling especially dense trying to follow the guide. 😔

**Comment by zorgiepoo** [comment]
The website docs have been updated here. You were looking in the checkouts/Sparkle/bin not artifacts/Sparkle/bin

**Comment by 101airborne** [comment]
I am having the same problem of not being able to find any such "artifacts/Sparkle/bin" path.

I am using Swift Package Manager in Xcode 14.2.  I did "Show in Finder" from Xcode's File Navigator on the Sparkle 2.4.2 package, but can find no indication of any "artifacts" folder anywhere.  The last post in this thread says that the documentation has been updated but I see no such clarification of how to find the required "artifacts/Sparkle/bin" directory in https://sparkle-project.org/documentation/ 

The documentation just says: "Run ./bin/generate_keys tool (from the Sparkle distribution root)." but not how to find the "distribution root".

The following is a screenshot of the Sparkle package Shown in Finder:

![Screen Shot 2023-07-31 at 2 04 32 PM](https://github.com/sparkle-project/Sparkle/assets/4751331/fb03b40c-33ec-426f-887b-b61256f37109)

Note: The only reason I am trying to generate EdDSA is because my app gets "Serving updates without an EdDSA key and only using Apple Code Signing is deprecated…" at app start-up. It is unclear to me if the EdDSA is absolutely required yet, so I thought I would eliminate that as the possible reason I am having other issues with Sparkle.

Thanks for any light that anyone can throw on my problem.

**Comment by 101airborne** [comment]
Thanks Zorg!  I totally missed the need to go up a directory.  Your tip allowed me to generate_keys and eliminate the "Serving updates without an EdDSA key and only using Apple Code Signing is deprecated…" message that I was getting in the console log.
