### ISSUE TITLE
Recommended version

### ISSUE THREAD

**Issue by jeff-h** [sparkle-project/Sparkle#1787]
I'd like to include Sparkle 2 in a brand new app. I haven't used 1.x before so would rather go straight to 2.x given that it appears to be so close. I've read everything I can find but I'm finding it hard to get started.

I was hoping to include v2 via SPM but that results in an error ([same as here](https://github.com/sparkle-project/Sparkle/issues/1718)). I'm guessing it needs releases for SPM to work? If so, would it be possible to actually make a release of the 2.x branch?

Otherwise, should I `make release` inside the 2.x branch and manually include the `Sparkle.framework` (and corresponding `.dSYM`) in my project? I guess `SparkleCore.framework` and `SparkleCore.framework.dSYM` as well? Anything else?

Thanks everyone for the fantastic work on 2.x!

**Comment by zorgiepoo** [comment]
v2 doesn't have official releases currently (and SPM / package management support isn't quite caught up yet). `make release` is currently the way to build a `Sparkle.framework` version of it as you presumed. v2 is in a "beta" state and most apps that use it are likely sandboxed (because v1 doesn't support sandboxing). Historically 2.x and 1.x branches have diverged, but that gap has been mostly closed up now.

SparkleCore is a stripped version of Sparkle without UI provided bits, so one would only use SparkleCore instead of Sparkle to write their own UI (or lack of one).

If you sandbox your app, you need to use some of the XPC Services. More details are on Sparkle's [documentation website](https://sparkle-project.org/documentation/).

**Comment by jeff-h** [comment]
Thanks, really appreciate your time explaining this.
