### ISSUE TITLE
Error auto-update not configured

### ISSUE THREAD

**Issue by GamingWithBradleyAndAdamYT** [sparkle-project/Sparkle#1825]
I was just on my laptop and out of no where a error message came up. What was interesting about this error is that it looked like it had to do something with Terminal, Bartender, and Sparkle. I'm not a expert at terminal so I don't know what any of this means. I also decided to go to the link and I was met with Sparkle. And although I wasn't familiar with sparkle I was familiar with logo I have LastPass installed on my laptop and whenever there is a update it looks like the picture on the sparkle website
I found another guy who is having basically the same problem the only thing that is different is his says "For security reasons, you need to code sign your application" He is a developer so that's why it says "your application". Also here is the other guy that is having the same problem: https://github.com/sparkle-project/Sparkle/issues/1549 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/74463271/114708966-0552c680-9cfa-11eb-8f77-bab04d94a162.png">

**Comment by zorgiepoo** [comment]
>  He is a developer so that's why it says "your application".

Actually, I think we added the application name in the message since then to clear up confusion for circumstances like this..

Sparkle doesn't think "Bartender" is code signed, and it does not think it has an EdDSA key, so updates will not work properly.

Curiously, if I download Bartender 4 trial from their website, their app bundle looks OK -- it has both a Sparkle EdDSA key, and it's code signed properly.

The dialog is also supposed to show the icon of the calling application which should be Bartender's icon, not that Terminal icon. I don't know what's going on there.

So either your copy of Bartender is bad maybe, or there is something else on your computer called "Bartender" and it's something else and tries to use Sparkle.. I'd be weary of using any "cleaner" apps.

**Comment by GamingWithBradleyAndAdamYT** [comment]
It is a legit copy of Bartender. But I've just uninstalled the app because its purely for looks.
