### ISSUE TITLE
hdiutil: attach failed - Device not configured

### ISSUE THREAD

**Issue by maxisme** [sparkle-project/Sparkle#1852]
## Summary

Hello,

I am getting the error: `hdiutil: attach failed - Device not configured` when updating with this endpoint - https://dev.notifi.it/upgrade?develop

<img width="435" alt="image" src="https://user-images.githubusercontent.com/16902919/117338235-3c9a3a80-ae96-11eb-9eeb-9f451d356a3c.png">

Any ideas what is wrong?

## Possible Fix

N/A

## Version

`Sparkle (1.26.0)`

**Comment by kornelski** [comment]
Maybe your dmg file is incorrect?

We don't really have any control over what `hdiutil` does.

If you can, switch to `zip` or tarballs. They're much faster, more reliable, compress better, and are much better integrated with Sparkle. From Sparkle's perspective they're superior to dmg in every single way.

**Comment by zorgiepoo** [comment]
Also make sure it's not because you're trying to sandbox your app (Sparkle 1 doesn't support sandboxing). There may be more detailed logs in Console app when the error occurs.

Like Kornel says, zip/tarballs is more efficient / reliable for Sparkle. However dmg is still good for distributing your app on your website.

**Comment by zorgiepoo** [comment]
Closing due to belief in sandboxing.
