### ISSUE TITLE
Make SUAppcastItem initialisation public

### ISSUE THREAD

**Issue by tonyarnold** [sparkle-project/Sparkle#1869]
### Description of the problem

ab294d607dbd8d26dce6d394386b13a6985fc8cc made the initialisation methods for `SUAppcastItem` private. I was using these methods to inject upgrade/re-subscribe notices into my update feed so that users who weren't eligible for an update weren't presented with versions they couldn't use.

Please consider making these init methods public (or even open).

### Do you use Sandboxing in your app?

Yes. 

### Version of `Sparkle.framework` in the latest version of your app

Version 438f4a21d5b52596b899d9931525c02a691b2287.

**Comment by zorgiepoo** [comment]
Ahh sorry my bad. Is your needs related to recent support for major upgrades? Particularly #1850, #1853, [`sparkle:minimumAutoupdateVersion`](https://sparkle-project.org/documentation/publishing/#publishing-an-update) (not completely updated regarding two other changes).

Which sparkle delegate call are you obtaining an appcast item and then constructing a new one based on that..? (Or at least little more context here on usage may be helpful).

There's another ongoing PR (#1862) and future changes that could conflict with making this initializer public and "correct". 

I don't mind exposing the method again for compatibility sake though, possibly deprecating it for sake of correctness and if there are other ways to support your use case.

**Comment by zorgiepoo** [comment]
Thanks for the info. I had guessed it was intercepting that delegate method but wanted to make sure :).

So I ultimately want Sparkle to move to providing solutions in the appcast feed to common/important workflows rather than clients using that delegate method and to return a newly created appcast item (which I was sort of weary of). Our support for that delegate method has historically been complex/buggy; for example until very recently we didn't pick delta updates properly or filter for minimumSystemVersion when letting clients to pick the best valid update. Having fixed these (and other) issues in the general case correctly, I may have even possibly broken it for some other case. Allowing clients to return items they construct themselves adds more room for error.

Some solutions I want to extend:
* Mark updates to be critical in the feed optionally based on being on < specific app version
* Mark updates to be informational-only in the feed optionally based on being specific set of versions
* Mark updates belonging to a set of channels/tags (eg: "beta") that are excluded by default
* Mark major upgrades (more on that in a bit.)

Allowing clients to construct their own app cast items may interfere with #1862 and allowing us to store auxiliary state in there (this simplifies some things, like I can implement the above critical/informational extensions without deprecating the current properties, and reduces number of objects we need to pass around / expose to APIs).

So for compatibility I still want to expose the initializer you need; just that the appcast items that are constructed may not correctly report new features that depend on the host version. So it may need deprecation.

> Is there a better way to handle this? I didn't quite follow the conversation on #1853 - the concept of skipping updates to stick to minor updates seemed a bit confusing.

Recent support for major upgrades works as follows:
* Available minor updates are always preferred over available major updates
* Major updates are not automatically downloaded or installed
* Users are notified of major updates and can choose to install them through Sparkle
* Users can choose to skip major updates, provided they confirm that they want to opt out of future scheduled alerts for further updates to that major update

**Comment by zorgiepoo** [comment]
Thinking more about this for major upgrades, or updates in general, it may also make sense to have some sort of UI hook on install a developer can intercept to confirm the user really wants to install a upgrade or do something like upgrade their license based on their current license state or such..

I don't think making major/paid updates informational-only or directing users to the product website is an ideal way of updating an app. I'm aware that's what plenty of apps must be doing and may have been the best suited approach though, at least at the time. And unfortunately few apps change their product name and bundle ID altogether..

**Comment by tonyarnold** [comment]
> I'm aware that's what plenty of apps must be doing and may have been the best suited approach though […]

Pragmatically, we work with the tools we have - so if you design an API that flexible, people will use it flexibly 😀 

> […] it may also make sense to add some sort of UI hook on install a developer can intercept to confirm the user really wants to install a upgrade […]

I completely agree that some kind of more formal implementation or delegate for indicating to the end user that the update they're about to install would require a new license, or cost them money would be the best outcome. It still might need to direct to the website, but perhaps there could be hooks for allowing developers to direct users to an upgrade payment workflow or similar? I'm not a fan of subscriptions and big timed updates, but the reality is that a lot of us are working on products with that kind of setup.

**Comment by zorgiepoo** [comment]
If that update that may require a new license or cost money could even apply to a "minor" update conditionally (depending on time expired), then basically the approach you were using is the only thing I can think of that would work currently. On the other hand the story is different if you only care about when, say `appcastItem.isMajorUpgrade` is true.

I think we should continue to export the designated SUAppcastItem initializer, but if I break the current one and need to add/export a new one, I'll need to deprecate the old ones and I may add the new one in the `PrivateHeaders` part of the framework to mark the support of it so to speak (usable if you import the header but discouraged).
