### ISSUE TITLE
Sparkle 2 runs in root space environment

### ISSUE THREAD

**Issue by bongibong** [sparkle-project/Sparkle#1882]
Im having an issue moving from sparkle 1.23 to Sparkle 2.0.
The environment is different and its a problem for us because we are using python and pip installation in post/pre scripts and we get a different locations.
For example the last line in the install log I attached is detecting the user_site:
(from the preinstall script: python -c "import site;print site.USER_SITE")
USER_SITE=/var/root/Library/Python/2.7/lib/python/site-packages 
While we used to get with Sparkle1:
USER_SITE=/Users/bongi/Library/Python/2.7/lib/python/site-packages

Every line in the log that has /var/root/.. used to be /Users/myUserName/..
I also noticed that the extracted location was ‘org.sparkle-project.Sparkle/PersistentDownloads/’ and with sparkle2 its ‘org.sparkle-project.Sparkle/Installation/’

We are using pkg. I define the xml:
sparkle:installationType="package"

Can I somehow work in the previous user space mode?
**[sparkle2_install_log.txt](https://github.com/sparkle-project/Sparkle/files/6760237/sparkle2_install_log.txt)**

**Comment by zorgiepoo** [comment]
I think it might be an incident that Sparkle 1 doesn't run in root space (using AuthorizationExecuteWithPrivileges()).. So that may be expected as the package gets executed from a root-running daemon now. 

I'm not sure where the docs are on creating installer packages or if there's some environment variable available to help you determine the user session.

Unrelated which I'm sure you are aware of system provided python's deprecation and future removal in macOS.

**Comment by zorgiepoo** [comment]
Maybe also see if `$USER` or `$HOME` point to anything useful but these are just guesses..

We submit our daemon tool with a job dictionary to launchd here:
https://github.com/sparkle-project/Sparkle/blob/2.x/InstallerLauncher/SUInstallerLauncher.m#L263

Potentially we could pass environment variable options if needed..

**Comment by zorgiepoo** [comment]
OK, I think I understand this issue. This issue does not occur if you run the pkg installer normally correct?

I think the issue is we don't preserve `$HOME` and `$USER`. I believe we can fix this by overriding those values (just for the `installer` task). `sudo` doesn't override these for example unless you pass `-H`.

**Comment by zorgiepoo** [comment]
Potential fix in #1884.

**Comment by bongibong** [comment]
Thanks @zorgiepoo for your answers.
indeed the same pkg installer runs without that issue when running manually.(not from sparkle updater)
also i verified that $HOME is pointing to /var/root now when it points to /Users/bongi not from sparkle or from sparkle1.x

I will try the fix that you pointed out and will update here..

**Comment by bongibong** [comment]
@zorgiepoo your fix looks great!!!
both preinstall / postinstall behaves correctly with the local HOME and USER vars.
Thanks man for the super quick response..
how can i help in merging this change??

**Comment by zorgiepoo** [comment]
Thanks, done :)
