### ISSUE TITLE
sparkle framework can't be opened.

### ISSUE THREAD

**Issue by jnseward** [sparkle-project/Sparkle#1916]
When I launch my universal Mac app MailSteward which uses the sparkle.framework, this message appears: “Sparkle.framework” can’t be opened because Apple cannot check it for malicious software.
![Screen Shot 2021-08-12 at 11 52 34](https://user-images.githubusercontent.com/1952432/129265191-6ece67e9-6154-4935-814e-69b858e78849.png)

**Comment by zorgiepoo** [comment]
Never seen that before. Are you code signing and notarizing your app from Xcode's archive organizer?

**Comment by jnseward** [comment]
Yes, code signing and notarizing from Xcode organizer. The message comes up on both my M1 Macbook Air running Big Sur and on my Intel mini running Monterey. However it does not come up on my friend’s M1 mini running Big Sur.

**Comment by jnseward** [comment]
If I click on Show in Finder, it shows the sparkle.framework file in the project folder for the MailSteward app. Also the app works just fine, including Sparkle.

**Comment by zorgiepoo** [comment]
Please check the Apple Code Signing section of https://sparkle-project.org/documentation/ and verify the output of the codesign and spctl commands on your application. Try to verify that the code sign identity of `Sparkle.framework` inside your app uses the same identity as your outer app bundle too (I believe `codesign -dvvv` can give this Authority information)

Otherwise my other guess is you may need to clear the quarantine of Sparkle.framework you downloaded before integrating it in your app.

`xattr -r -d com.apple.quarantine Sparkle.framework`

But that sounds fishy.

**Comment by jnseward** [comment]
Thanks. Clearing the quarantine did the trick.
