### ISSUE TITLE
Sparkle 2: Support JSON appcast format

### ISSUE THREAD

**Issue by ezekg** [sparkle-project/Sparkle#1980]
## Summary

Follow up to these old issues, #1080, #905, #427, #155. It seems to have been requested for years. I figured a new thread would be nice, especially since Sparkle 2 is under development. I'd really like to see support for a JSON appcast. XML is old and constantly has new security issues, and it's really tough for new APIs to support it due to this. Adding JSON support would really modernize Sparkle, especially from the perspective of a software distribution service, which is nowadays typically some sort of JSON-based API backed by a storage service such as AWS S3 using a non-public storage bucket i.e. signed URLs per-asset (for example, this is how services such as GitHub Releases operate, for public and private repos).

## Possible Fix

Allow an update server to respond with JSON instead of XML. Ideally, we could allow the server to respond with _any_ payload, by offering a way to delegate transforming an arbitrary server response into an `SUAppcast`. This would allow Sparkle to support nearly any distribution server, including more modern setups like AWS S3 using signed URLs, or GitHub releases, since the developer could transform response values into a valid update. But if that's not feasible, we can define a required or default schema that a server must follow for JSON response formats.

With that said, I see 2 really good choices: (feel free to chime in with thoughts)

1. Add support for defining a delegate to parse the update server response and transform it into a valid `SUAppcast`. This delegate could make additional requests if needed, or simply parse the custom server response, possibly JSON possibly not, into an `SUAppcast` with valid `SUAppcastItem` items. E.g. add `SUAppcast:initWithDelegate`.
2. Add `SUAppcast:initWithJSONData` much like `SUAppcast:initWithXMLData`.

Both would be ideal, since 2 could be an implementation of 1, i.e. an out-of-the-box standardized JSON delegate. Having 2 would open up the door for third-party delegate packages, to support the various distribution services that all have different response formats and access requirements. This would put the onus on third-parties to build and maintain delegates, instead of the Sparkle team, who would only maintain the XML and possibly the official JSON delegates.

## Version

Sparkle 2

----

Disclaimer: I'm a small business owner, and I currently run a software distribution API service. I'd really like to natively support Sparkle for my macOS customers. But I would like to avoid implementing a custom server endpoint that responds with XML solely to support Sparkle, so I'm opening this issue to start the conversation around Sparkle 2 supporting a wider variety of update server response formats, by allowing the community to build out appcast delegate packages to support services such as GitHub Releases, S3, R2, as well as my own service.

Please forgive me if I don't fully understand Sparkle’s internals. I'm new to the code base, and to Swift/Obj-C, but have been reviewing it over the last months to try and come up with a feasible way forward here.

**I am willing to put a bounty on this of $1,000/mo, to fund development, given the Sparkle maintainers approve of the final direction that should be taken.**

**Comment by zorgiepoo** [comment]
Sorry I don't really want to support creating custom mappings of properties or expose appcast item creation to clients. This also fragments other support / Sparkle-based tooling. This is a bigger ask than JSON support which you can see hasn't been done yet. I am more open to supporting JSON as a secondary standard format, despite its shortcomings if they can be worked around..

I don't think signed appcasts can be complicated enough to require web server sending custom metadata back. Including the signature in the appcast is possible, possibly, if the signed contents strips out the signature field and Sparkle strips out contents on verification.. This is definitely less pleasant and possibly less secure than an XML comment to me. Ok, I can think of ways around this though, let's move that aside..

Thinking about it again, embedded release notes support is also important (eg look at the one the Sparkle Test App uses), even if it's not as pretty in JSON.. Apps do use this today and it's also somewhat related with signed appcasts.

**Comment by zorgiepoo** [comment]
The appcast format is a big part of Sparkle -- maybe not code-wise, but lots of other infrastructure & services (eg brew-task, macupdate, other implementations of Sparkle for other OS's, more) rely on it. Other software that updates user's software for them rely on it. Sparkle 2 even includes an API and a tool to update other Sparkle based bundles. People even subscribe to software update feeds with RSS readers. I debug other people's apps when investigating Sparkle issues. Asking for a way to customize the appcast format is going to fragment support for all these other use cases. Further allowing custom mappings causes fragmentation by allowing these different formats or backends to not implement specific features, despite the framework otherwise supporting it, which users may need but don't know it just yet and realize too late.

I don't want to also maintain API support for that customization or maintain compatibility with other mappings, and I don't want users to be tied to a "middle-man". I have recently even been making the details of creating appcast items / appcasts private and not exposed to minimize past misuse and future compatibility breaking changes.

generate_appcast could probably indeed handle serializing out inline HTML in JSON.

I bet a big part of people wanting JSON support over XML actually is that it's easier to read, write, modify, and validate by eye. So I disagree about the "pretty" statement. All the test appcasts I use are crafted or altered later or copied/pasted by hand and no doubt other developers do this too for their own software. People like to make claims in their favor like nobody should be modifying appcasts by hand, or comments are not used by people, or who uses (or writes by hand) embedded release notes -- but the fact is these things are untrue and they are very important to consider in making a good assessment of benefits/shortcomings here.

I realize we also have somewhat different goals.. I care more about the app developer experience of integrating Sparkle, not so much about backend providers adopting Sparkle... I don't really believe supporting a standard JSON or XML format is a significant issue for them.. and needing to provide an additional API to users to understand a custom format has costs from my point of view.

**Comment by ezekg** [comment]
Okay, thanks for your time. 👍

**Comment by jbrayton** [comment]
Hi Zeke,

I just wanted to check in and see if you were still hoping to hire me to work on a Keygen SDK for macOS over the next month or two? Please let me know.

Thank you, and happy Thanksgiving.

John
