### ISSUE TITLE
Clients polling rapidly - began ~Oct 26...

### ISSUE THREAD

**Issue by herf** [sparkle-project/Sparkle#1986]
I am seeing a big uptick in clients polling our Appcast in a loop (growing rapidly over the last three days, beginning around Oct 26). A single client can generate 500,000 requests per day (we drop these clients at the firewall). Right now, we are blocking hundreds of IPs. My shipping version is Sparkle/1.24.

The symptoms:
- About 4% of clients have a user agent of "Sparkle/?" implying "displayVersion" is failing somehow.
- Previously I had about 1.8% of clients with "Sparkle/?", but they did not poll, they just acted like normal clients. Now there are more of them and they poll.
- Darwin versions for the high-traffic clients include 20.6.0, 20.5.0, 20.3.0, and 21.1.0 (so Big Sur and Monterey) but older versions still sometimes send "Sparkle/?" as UA.

These "Sparkle/?" requests seem to be using separate cookies than the ones that were sending a version, so it's like they're suddenly getting sandboxed out of the filesystem or something like that. Also, some of the clients sending system configuration (the random sample) are sending "Sparkle/?" so I think it's less likely that a third party (like Homebrew cask) is at fault, because the system information looks an awful lot like Sparkle.

I've tried running my app from Downloads/ while denying it access to Downloads, but Sparkle just popped up a nice error. I'm thinking something like this security-wise has changed, but looking for any clues (or maybe bugs that are fixed in newer versions!)

Thanks for any help.

A much older version of this bug was #1061

**Comment by zorgiepoo** [comment]
#1992 and #1991 for that. I still don't have an idea of underlying issue but it could help.

**Comment by herf** [comment]
When I "slowloris" the updates, I am still seeing multiple connections, overlapping.

I think the paranoid approach is to assume something in macOS security has totally disconnected the filesystem - so NSDate and NSUserDefaults cannot be touched in the worst-case "retry" path. Can we force delays that don't depend on the filesystem?

**Comment by zorgiepoo** [comment]
We already don't trust NSUserDefaults in the re-try path. I just pushed changes in to not trust NSDate in the common re-try-loop path too (#1991).

We still need to rely on a timer of some sort to schedule the next update. The alternative to that is you can disable automatic checks for updates (`SUEnableAutomaticChecks` to `NO`) but then you'd have to be in charge for when to make update checks in the background (`checkForUpdatesInBackground`). Or you can decide to start the updater itself at some point later if you think it will help you (if it's an early initialization problem).

I would also not call a SUUpdater initializer (or sharedUpdater) more than once. Theoretically in the 1.x branch SUUpdater is a singleton anyway and shouldn't be an issue in practice, but as we're on the discussion of code paths to avoid..

**Comment by zorgiepoo** [comment]
The other thing I can think of is if NSURLSession has some automatic retry logic of sorts but don't know enough about this offhand.

**Comment by herf** [comment]
I do like the NSDate changes - however, if you were able to generate a lot of "wake" events or some crazy thing, you'd still wind up with:

SUUpdater.m:
  delayUntilCheck = 0; // We're overdue! Run one now.

Is there any harm in fuzzing the "second time" out to 60s +/- 15s or something like that (so only first launch, or user-initiated one would be instant)? I imagine when I wake my machine it may still be renewing an IP address and so a small delay here would not seem to be harmful.

And from the perspective of 10 requests/second, one per minute worst case would be a big improvement!

**Comment by zorgiepoo** [comment]
Maybe do-able, but not if update cycle is reset by eg user enabling automatic update checks or changing update check interval (in that case there is a 1 second delay). And not on launch. If the concern is about receiving wake notification, then maybe it makes more sense to put a 15sec delay there and cancel any previous invocations of this. On another note 2.x uses a dispatch source timer (based on wall-time) instead of NSTimer so these sleep/wake notifications handlers are ultimately going to be removed going forward. From previous experience though I know these notifications are only supposed to be for deep sleep / wake and not dark wake / power nap, so frequent sleep/wake events aren't supposed to happen.

**Comment by zorgiepoo** [comment]
You can check https://github.com/sparkle-project/Sparkle/pull/2000, I don't have time to validate it right now and it's incomplete in terms of being merged.

Still there's a chance that *something else* is going wrong, so at some point of adding paranoid checks here, I become weary when it creates additional complexity to maintain.

**Comment by zorgiepoo** [comment]
Btw, this is all likely unrelated but, if the app in question here is Flux, its sparkle:version in the feed is not matching the download / latest version. And it's trying to set minimum OS deployment version to 10.7 with macOS 11.1 SDK, but recent Xcodes (12-ish) no longer support compiling/deploying < 10.9 minimum OS

**Comment by herf** [comment]
Yes, it is f.lux - we do a lot of conditional updates server-side, so sometimes we leave a machine on an older version when a fix is not important (like if it affects 1% of users). I think our latest update was trying to keep 10.8 working, but we'll probably have to drop it soon for 10.9. I was patching in SDKs into old Xcode builds, so it probably looks weird.

We have settled at around 11% "Sparkle/?" IP addresses, up from 1.8% before whatever happened this week.

Regarding the bug - I will push out some 1.27rc's soon and test your more careful versions. Thanks!

**Comment by zorgiepoo** [comment]
I updated #2000 (and #2002 for 2.x) to use a monotonic clock to enforce a safe minimum delay. The idea is that while the wall clock may be a potential source of unreliableness (but often desired), the short monotonic delay will prevent rapid successive scheduling.

**Comment by zorgiepoo** [comment]
So I overheard a developer running into issues with users having CleanMyMac installed and their application's appcast being queried *a lot* due to this. Curiously I checked out their application (didn't actually run it), and noticed they have a [feature](https://macpaw.com/support/cleanmymac/knowledgebase/updater) to update apps on the system. Secondly I noticed they include Sparkle.framework in a couple places but what they contain is heavily forked, and they stripped lots of the resources files, moved a couple things around, and modified the Sparkle code. It's possible they use this to update the apps.

Their Sparkle.framework Info.plist looks literally like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict/>
</plist>
```

So this is one such way `?` can show up as the `kCFBundleVersionKey` (although this developer did not witness this occur).

This is all just speculation though but it's possible for users to install popular tools that do these sort of things..

**Comment by herf** [comment]
Thanks - this is a good theory - of course a fork of Sparkle would "look like" Sparkle. And also we are back down to 1.8% of IP addresses sending "Sparkle/?" so it's possible that a third party updater is involved at that rate.

**Comment by herf** [comment]
From the latest version of f.lux (shipped with Sparkle 1.24):

- 92% of clients report "Sparkle/1.24" as expected
- 6% of clients report "Sparkle/1.19.1" (which we did ship a couple years ago)
- 1.8% of clients report "Sparkle/?"

So one more possibility: are there any bugs that would cause an older Sparkle to fail to update itself, inside a bundle? This gets complex with notarization. If so, we might be able to notify them to reinstall. Or should we assume a third party updater?

**Comment by zorgiepoo** [comment]
The developer I overheard this from (they've since contacted cleanmymac folk) had a snippet showing `Sparkle/1.19.1` however I don't have enough data to confirm it's a third party updater (but there is this similarity).

Of the 92% clients that report Sparkle/1.24 were you still seeing frequent polling?

**Comment by herf** [comment]
Nope - 1.22 and 1.24 are working as expected!

**Comment by zorgiepoo** [comment]
Well that explains everything now. I'm quite convinced this is due to third party updater/tool now. I'm not sure I'm going to keep those monotonic timing changes I merged recently now... Maybe. Otherwise I can't do much here that I can think of at the moment.

**Comment by herf** [comment]
Thank you for all the help, really appreciate it. Not sure we would have figured this out otherwise.
