### ISSUE TITLE
Xcode 12 is trying to codesign Sparkle.framework/Versions/A but it should be signing Sparkle.framework/Versions/B

### ISSUE THREAD

**Issue by rob-dodson** [sparkle-project/Sparkle#2069]
### Description of the problem
 
With Xcode 12.4, and Sparkle set up via SPM, at build time Xcode is trying to codesign Sparkle.framework/Versions/A but it should be signing Sparkle.framework/Versions/B. Versions/A is present but is an empty directory. 

### Sparkle's output from Console.app
```

```

### Steps to reproduce the behavior

[The more information provided and pasted verbatim, the easier it will be to diagnose an issue. If you can provide the affected application/binary and XML feed to reproduce an issue, share them]

**Comment by zorgiepoo** [comment]
We officially only support the latest version of Xcode 12 (12.5.1) or Xcode 13 at this time (basically the latest of N (beta or stable) and N-1). Our CI is running Xcode 12.5.1. I wager this is an Xcode bug that was fixed in 12.5.1.

I recall someone else on Catalina (being forced to use 12.4) running into this issue. If you want a workaround, I think you can change `FRAMEWORK_VERSION = B` to `FRAMEWORK_VERSION = A` in `ConfigFramework.xcconfig` and re-build. Sadly this may mean you cannot use SPM.

**Comment by rob-dodson** [comment]
Thanks, that is a big help.

**Comment by XericDesign** [comment]
This affected me too on Xcode 12.4. What is the reason for moving the framework to /B/ instead of /A/?

**Comment by zorgiepoo** [comment]
In the 2.0 betas we originally had the XPC Services bundled outside the framework for sandboxed apps and we transitioned to moving them inside the framework for much simpler integration. Because of a macOS bug the system did not invalidate a cache detecting the XPC Services were moved unless the system was rebooted or the newly installed app was moved to another location. We better worked around this issue by changing the version which changed the path to the Sparkle binary inside the app.

If your users were not running a version of Sparkle 2.0 beta's that had the XPC Services bundled outside the app (if you sandboxed the app), then you can safely change the version to A. I did not foresee that older Xcode versions would have a bug here. But on the other hand it's moving out of the window of the Xcode versions we support anyway.

**Comment by XericDesign** [comment]
Makes sense. I worked around it in 12.4 by turning off "code sign on copy" and using the manual signing under the Sandbox instructions. This actually fit into my flow well since I have a single project that builds for both the Mac App Store as well as a version for my own website that has to be notarized so I have been doing manual signing for a long time.

**Comment by rob-dodson** [comment]
I think you are saying no, but is there a way to change framework version if we are using SPM?

**Comment by zorgiepoo** [comment]
There is what XericDesign mentioned above but I don't know if SPM allows you to turn off code sign on copy otherwise you'd have to fork the repo and change some details about where SPM should look up a release and make a release on the fork..

**Comment by zorgiepoo** [comment]
Supported versions now are Xcode 13.4.1 and Xcode 14 (currently beta).
