### ISSUE TITLE
Online installer to avoid universal binaries

### ISSUE THREAD

**Issue by mherrmann** [sparkle-project/Sparkle#2085]
Hi!

Can Sparkle be used to create an "online installer"? So not for performing an update, but to perform an initial installation. The idea would be that the user downloads a small (say 1MB) file that uses Sparkle to download and install the latest version of an installation. This could be especially interesting as a solution for avoiding the download-heavy universal binaries: The installer could check the processor type and download and install the appropriate version.

Thanks,
Michael

**Comment by zorgiepoo** [comment]
Sparkle is for installing updates from an existing application, not for initially installing an application. There's no support for the latter.

I know some projects like to not use universal binaries to save space (eg a plethora of Electron apps) but this is also fighting the grain against macOS.

How much % increased is the UB for Brave, and how much % increased is that when it's compressed? Are you willing to pay the one-time cost of having an initial large download but smaller updates later? (The app seems already pretty big to me regardless of universal binary).

There are a few general things you can do to save space that we (or will) support:

* For updates you can use a format with [optimal file compression such as .tar.gz (LZMA compression)](https://sparkle-project.org/documentation/publishing/#archive-your-app). You may not want to use this for website/initial distribution though, because users may look at you funny. This will also likely be faster on the decompression side than a bzip2'd dmg file.
* You can use [binary delta updates](https://sparkle-project.org/documentation/delta-updates/) for ultra-small and fast updates past the initial installation. I can tell by looking at Brave which likely is bundling version-changing frameworks (chromium?), delta updates won't be worthwhile until our version 3 binary delta format is out, which better tracks content moving around. It is [currently released in 2.1 beta 1](https://github.com/sparkle-project/Sparkle/releases/tag/2.1.0-beta.1) for developers like yourself to test out.
* If you are concerned about the disk space usage of your post installation, you can significantly reduce the amount of space it takes up by using HFS+ / apfs file compression. You can try using `ditto --hfsCompression Brave\ Browser.app Brave\ Browser\ Compressed.app` to try it out. Get info on both apps and under `Size:` it will tell you in parentheses how much space is being used on disk (in your case, Brave Browser's disk space gets cut in half). All the apps on the Mac App Store ship this way to my knowledge. This transparent file system compression does not get preserved in zip files, so you will have to use `.tar.*` (recommended) or `.dmg` to preserve the compression. Our delta format currently does not preserve HFS+ file compression however, but this is already fixed in our repo and planned to be in 2.1 beta 2 which I will release soon.

Other than of all that, all other optimizations are specific to your app.

**Comment by mherrmann** [comment]
Thank you for your explanations. In case someone else has perhaps "hacked" Sparkle to get an online installer, it would be great if they would be willing to share some experiences.

**Comment by zorgiepoo** [comment]
Any sort of installer is going to lead to a worse user experience. Mac users do not like them.

Really I would spend engineering effort on figuring out why your app is big (if that’s your concern) and how to reduce it in ways that don’t involve splitting your archs. For Sparkle this may involve eg making sure headers are stripped when copied to the app bundle, optionally removing unused localizations, unused xpc services (in sparkle 2). The rest of your app bundle is likely an exercise of your own to better understand.
