### ISSUE TITLE
Could Sparkle keep checking if there are newer versions after downloaded, extracted next version.

### ISSUE THREAD

**Issue by cenkayberkin** [sparkle-project/Sparkle#2092]
I apologize if the title sounded confusing :)

Currently using Sparkle 1.26

My questions is, lets say we are doing auto updates, and not showing any pop ups to users (not using delta updates also):
- our app is at version 1, and we see that there is version 2 available,  Sparkle downloads and extracts the update, ready for installation when app quits.
- User doesn't quit the app for sometime and now update 3 is deployed on service side.
- Sparkle doesnt seems to keep on checking newer version anymore once it downloaded the update.

**Does it support such scenario ?  If users dont quit their app and if there are frequent updates, this would be very usefull.**
- Check periodically , if there are newer versions then in ~/Library/Cache ... , 
- if there arent then do nothing, if there are download them in separate folder and extract and notify when ready.

Does version 2.1 support such scenario ?? Thank you so much in advance for your answer

**Comment by zorgiepoo** [comment]
It’s not currently possible. Probably only makes sense for updates downloaded in the background silently because otherwise you will have strange and complicated UI implications. Consider this a feature request. It would involve replacing the current version staged to be installed with a newer downloaded update and more periodic update checks.

**Comment by zorgiepoo** [comment]
I don't see this worth investing in.
