### ISSUE TITLE
Notarization failing on complex app build

### ISSUE THREAD

**Issue by jon-blum** [sparkle-project/Sparkle#2097]
### Description of the problem

I've got a rather complex app which we've made available as a utility to clients, and now want to distribute through the web.  Sparkle has been working fine in practice in the app -- but now that we want to get the app notarized, Xcode is unable to find a signing profile for Sparkle's AutoUpdate.app.

### Do you use Sandboxing in your app?

Some components (e.g. FileProvider extension) are sandboxed, but the app package as a whole isn't.

### Version of `Sparkle.framework` in the latest version of your app

1.26.0

### Sparkle's output from Console.app

N/A

### Steps to reproduce the behavior

I'm using Sparkle 1.26.0, in XCode 12.5 on Big Sur 11.4.  Sparkle is installed using CocoaPods, which (if I'm following it correctly) means it's automatically code-signed with my certs when it's copied in by one of the CocoaPods scripts.  We need to distribute this app in an installer, so we will need a custom export workflow eventually -- but this is happening at a point when we're still inside the standard XCode workflow, on first notarisation.

Archive the app.  In the Xcode Organiser, choose "Distribute App".  In the wizard, choose "Developer ID", then "Upload".  The wizard proceeds to the "Select certificate and Developer ID profiles:" dialog.  I have to choose different profiles for the main app (com.orexresearch.EMPSecure) and the contained tools (com.orexresearch.EMPSecure.EMPFileProvider and com.orexresearch.orexfs.Mounter).  The other libraries and frameworks show up as not needing a profile -- except for AutoUpdate.app.  If I try to import one of my existing profiles, Autoupdate.app gives an error:  'Profile doesn't match bundle ID "org.sparkle-project.Sparkle.Autoupdate".'
<img width="1207" alt="Sparkle profile" src="https://user-images.githubusercontent.com/2071917/156545783-e59875f0-2bb6-4ebb-90c6-773c87dfd544.png">

(I can't create an AppID with that bundle ID -- the Apple Developer ID site reports that it's not available, obviously it's registered elsewhere.)

Do I need to remove the code-signing steps for the Sparkle pod entirely, or is there some other approach to fix this?

**Comment by zorgiepoo** [comment]
> ...means it's automatically code-signed with my certs when it's copied in by one of the CocoaPods scripts

I don't know if that's true or not but it's not relevant because Xcode's Archive Organizer re-signs your entire app bundle and all the executables inside it anyway (and with some correct settings applicable for deployment).

> We need to distribute this app in an installer, so we will need a custom export workflow eventually

Mac users do not like installers, they are highly discouraged. Many apps do not have a good reason for using them.

So I don't know much about profiles but Sparkle's helpers like Autoupdate.app shouldn't be signed with a special provisioning profile or anything, ideally. It sounds wrong to use the file provider profile on it. Autoupdate's certificate should match your main app's one, and/or use no special profile at all.

In the worst case if you can't figure out anything else you can modify the bundle ID to our helpers like Autoupdate.app and build your own version of Sparkle. I would also perhaps try to notarize a simple app embedding Sparkle, and compare differences..

**Comment by jon-blum** [comment]
Thanks for that -- could you tell me where I need to make the changes for Autoupdate's bundle ID?  That sounds like the easiest solution for now.  (Oh and for what it's worth, I get the same results whether I specify the main profile or the FileProvider one for Autoupdate -- they're both flagged as the wrong bundle ID for Autoupdate.)

Unfortunately we're stuck with the installer for now, because our utility includes a kernel extension -- we're in the process of redesigning the whole app to replace the virtual-drive kext completely with the FileProvider extension, but in the meantime we still have to use the installer to install and approve the kext!  (And as long as we support pre-Big-Sur versions, those won't be able to use FileProvider.)

Thanks,
Jon

**Comment by zorgiepoo** [comment]
From #1885 it sounds like I would also try to make sure to not sign Autoupdate with a certificate that's not ad-hoc before the archive process (you'd actually have to go out of your way to do this, via some script).

For Sparkle 1, you can add a new entry and set PRODUCT_BUNDLE_IDENTIFIER in ConfigRelaunch.xcconfig 

For Sparkle 2, the Updater.app would be relevant so that would be again setting PRODUCT_BUNDLE_IDENTIFIER in ConfigInstallerProgress.xcconfig

Indeed, a kext while transitioning is a legitimate reason.

**Comment by jon-blum** [comment]
The #1885 case might actually be relevant -- as I said, I'm including Sparkle using Cocoapods, and a quick look at the Cocoapods script that's called on copy-in looks like it might be doing a sign-on-copy!  If so, I'll see if I can find a way around that, and see if that fixes the problem.  If that doesn't work, I'll look in ConfigRelaunch.xconfig and get back to you if that doesn't work.

**Comment by zorgiepoo** [comment]
Check `codesign -dvvv path-to-Autoupdate.app` to see if it's using an ad-hoc signature before Xcode's archive organizer / archive process re-signs your app.

**Comment by jon-blum** [comment]
Just a followup on this one -- yes, it turned out that CocoaPods' script, and my own Run Script phase, were both re-signing Sparkle.  Turns out the solution was:

Clone and build Sparkle from source.  (As usual, do *not* use GitHub's ZIP links to download it, because GitHub leaves out the dependencies; I had to clone the repository, and then switch to v1.26.0 to match the version I previously used.)

Change the PRODUCT_BUNDLE_IDENTIFIER as described above.  I also changed it again from “$(PRODUCT_BUNDLE_IDENTIFIER)” to “com.orexresearch.EMPSecure” in the Info.plist, and in “custom MacOS Application Target Properties” in the AutoUpdate target’s Info section, while trying to resolve later linking issues; those probably aren't necessary.
Added Sparkle.framework to “Frameworks, Libraries, and Embedded Content” on the “General” settings page of my main target.  Set the entry there to “Embed Without Signing”.
Removed it from my CocoaPods Podfile.
Removed it from the input and output files lists in “[CP] Embed Pod Frameworks” entry in “Build Phases”.

After this -- and after a further snafu where it turned out it was still picking up the old CocoaPods version of the framework from the path in "Framework Search Paths" -- I was able to build and archive the whole package, and select my main provisioning profile for Autoupdate.app.  The archive was successfully sent to Apple for notarization.

...And then failed because the settings are wrong for the kernel extension's cert, but that's a separate bug I'll have to chase down.  Thanks for your help!
