### ISSUE TITLE
How can I hide the Sparkle UI entirely in Sparkle 2?

### ISSUE THREAD

**Issue by SauravPahadia** [sparkle-project/Sparkle#2106]
## Summary

Migrating from Sparkle 1 to Sparkle 2. 

Our application silently installs updates in the background. When the user restarts the application, we compare the current version to the version stored in UserDefaults. If current version > last version, we display our own panel with our release notes. 

To do so, we're planning on using an SPUUpdater instance with our own SPUUpdaterDelegate passed in. However, SPUUpdater also requires us to pass in an SPUUserDriver, which we don't want to use since we show our own panel at a specific time that doesn't fit into the SPUUserDriver flow as far as I can tell.

Is there a way I can pass an empty SPUUserDriver into my SPUUpdater? Should I just pass in SPUStandardUserDriver and set some flag to disable the Sparkle UI? Do I need to override some method in SPUStandardUserDriver to prevent the UI from appearing?

I see mention of `SPARKLE_BUILD_UI_BITS=0` in this documentation: https://sparkle-project.org/documentation/upgrading/ but I can't find mention of it anywhere else.

Thank you!

## Version

Sparkle 2

**Comment by zorgiepoo** [comment]
> Our application silently installs updates in the background. When the user restarts the application, we compare the current version to the version stored in UserDefaults. If current version > last version, we display our own panel with our release notes.

This sounds fine to do independently from Sparkle.

> To do so, we're planning on using an SPUUpdater instance with our own SPUUpdaterDelegate passed in. However, SPUUpdater also requires us to pass in an SPUUserDriver, which we don't want to use since we show our own panel at a specific time that doesn't fit into the SPUUserDriver flow as far as I can tell.

> Is there a way I can pass an empty SPUUserDriver into my SPUUpdater? Should I just pass in SPUStandardUserDriver and set some flag to disable the Sparkle UI? Do I need to override some method in SPUStandardUserDriver to prevent the UI from appearing?

Sparkle (both 1 and 2) have a few flows that may bring up UI that you may want to consider:
* User manually checking for updates - in this case, I assume you may not want to provide this functionality.
* An update that has been downloaded/to be installed in the background, but hasn't been installed for a long time (a week if I recall correctly) because the app hasn't terminated - in this case, Sparkle's scheduler nudges the user to install the update after this lengthy time. There are a couple ways to opt out of this.
* An update prompt will be shown when Sparkle needs to request the user to authorize installing the update due to otherwise insufficient install permission (e.g, a guest user updating an admin-owned app, or an admin user updating a root-owned app set up in whatever one-off case environment).

Because of the third case UI cannot be avoided entirely, unless you want to disable updating for this flow which I suspect you don't.

You can implement [the appropriate updater delegate method](https://sparkle-project.github.io/documentation/api-reference/Protocols/SPUUpdaterDelegate.html#/c:objc(pl)SPUUpdaterDelegate(im)updater:willInstallUpdateOnQuit:immediateInstallationBlock:) to stop Sparkle's scheduler for the 2nd case.

Stopping Sparkle's scheduler would block checking for updates manually from Sparkle however. If you want to also provide this option I can elaborate more on an alternative on the SPUUserDriver side that would dismiss updates from the 2nd case.

**Comment by SauravPahadia** [comment]
Thanks for the info on these cases. 

My question is a bit more generic - will the standard Sparkle update UI appear after an update was downloaded in the background if I pass in an standard SPUUserDriver?

**Comment by zorgiepoo** [comment]
it's really the same question, answer is yes in the 3 specific cases above.
