### ISSUE TITLE
Checking for updates manually doesn't show downloading UI when SUAutomaticallyUpdate=true

### ISSUE THREAD

**Issue by mikehearn** [sparkle-project/Sparkle#2116]
## Summary

I believe this is what's going wrong but please correct me if the error lies between keyboard and chair.

With SUAutomaticallyUpdate and SUEnableAutomaticChecks set, Sparkle will download updates in the background with no UI visible, then prompt the user once the download is complete to restart the app. Great. However, with these keys set (in the `Info.plist`) if I call `[[updaterController updater] checkForUpdates];` then this triggers the exact same process i.e. no UI visible and nothing appears to be happening although in reality a download is occurring and UI will appear once it's complete.

## Possible Fix

Unless this is a config/usage issue, the fix would seem to be to ignore the "ui-less download" setting when a manual check is invoked, or allow the settings to be overridden via the API. There's API to change SUAutomaticallyUpdate at the moment but it's really meant for setting user preferences.

## Version

Sparkle 2.1.0

**Comment by zorgiepoo** [comment]
> With SUAutomaticallyUpdate and SUEnableAutomaticChecks set, Sparkle will download updates in the background with no UI visible, then prompt the user once the download is complete to restart the app. Great. 

If the update requires user authentication or the update is critical or info-only, yes, the prompt will show up promptly. Otherwise the update will install when the app is terminated, or it will prompt up after 1 week if it hasn't been terminated/installed yet.

> However, with these keys set (in the Info.plist) if I call [[updaterController updater] checkForUpdates]; then this triggers the exact same process i.e. no UI visible and nothing appears to be happening although in reality a download is occurring and UI will appear once it's complete

canCheckForUpdates needs to be checked before calling checkForUpdates, that is why it's hooked up with menu item validation in our documentation. There is a brief period of time (while the update is downloading automatically in the background) where the update cannot be checked. So what is probably happening in your case is checkForUpdates ignores your call because the update is still downloading.

After the update is downloaded, you can check for updates and resume the update that was downloaded.

> There's API to change SUAutomaticallyUpdate at the moment but it's really meant for setting user preferences.

This is correct. Prefer Info.plist settings when possible.

**Comment by mikehearn** [comment]
Hmm. Right. Is there a way to pop up the download UI if it's presently hidden? I think the user would expect the check for updates option to always be available, and if it's disabled, they wouldn't automatically think "ah ha ... a download must be in progress. I shall wait patiently until it appears".

**Comment by zorgiepoo** [comment]
There isn't any off-screen UI created in that case, another path is taken for downloading updates silently. Sparkle isn't currently designed to operate in such a mode that a user can resume an on-going download from the background. There are some potentially awkward user interactions involved with adding such a mode too so I'm not even sure it's a good idea ("I wanted to check for updates, confusing how it's showing me downloading the update.." or "why is it showing me information about the update after downloading it" or instead "it's asking me to install the update but I've no idea what this new update is about")

The best thing presently you can do to reduce the lag is focus on optimizing your update payload (some tips from our [Publishing documentation](https://sparkle-project.org/documentation/publishing/#publishing-an-update) including delta updates).

**Comment by mikehearn** [comment]
OK. Thanks for the tips and the nice framework!
