### ISSUE TITLE
Bumping minimum macOS deployment target

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#2186]
Since Xcode 14 is raising the minimum supported deployment to macOS 10.13, we will need to raise it from 10.11 -> 10.13. The only question of doing this is when (ideally, to a release that aligns with Xcode 14 stable being released).

**Comment by ychin** [comment]
Hi @zorgiepoo I'm curious but where does it say that Xcode 14 requires 10.13? I tried this out locally and while the **GUI** seems to require 10.13, if you build using the command line, setting `MACOSX_DEPLOYMENT_TARGET` to lower versions still seem to work. I built it using 10.9 and it still works.

I'm asking because MacVim currently targets 10.9, and hence we are going to be stuck on Sparkle 1 for the foreseeable future (since Sparkle 2 requires 10.11), but I think unnecessarily bumping to 10.13 would make it even harder to make a switch to Sparkle 2 (A bump from 10.9 to 10.13 is a lot, especially since 10.9 - 10.11 had the same system requirement, but 10.12 and 10.13 dropped olded Macs).

If there are particularly new technology that had to be set to deploy against 10.13 I understand, but just want to make sure it's not just because of a misunderstanding.

**Comment by ychin** [comment]
Hmm when you compile using `xcodebuild` it does complain about it: 

> warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.1.

I wonder if this is a hard warning or just a "you should consider updating" thing.

**Comment by zorgiepoo** [comment]
It's in the [Xcode 14 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) that Xcode 14 cannot deploy back further than 10.13. There is even an [Xcode table on this](https://developer.apple.com/support/xcode/) which notes which versions of Xcode supports building apps that deploy to which OS versions. The last time this happened was when Xcode 13 raised the minimum deployable OS from 10.6 to 10.9.

It's very likely gated by technical reasons and that Xcode needs to have some support for backwards-deploying that goes beyond a mere version setting. You'd be on the safe side to assume any binary you build on Xcode 14 is incompatible below 10.13 regardless of trying to force `MACOSX_DEPLOYMENT_TARGET`.

Sparkle 2.0 had APIs I wanted to use that were 10.11+ only, and then eventually 2.1 used even more APIs that were 10.11+ only. Now as you can see this is moot because Xcode is going to force 10.13+ only binaries anyway. Using older versions of Sparkle or software when you need to support older OS versions is a fine strategy, but eventually requirements raise.. Personally speaking, I think 10.13 is pretty far back although it doesn't matter what I think in this specific case.

**Comment by ychin** [comment]
Ugh you are right. Thanks for pointing it out.

But yes 10.13 is old, but some of my users just refuse to upgrade 😅. We will think about what to do on our side.
