### ISSUE TITLE
Hide Version History button?

### ISSUE THREAD

**Issue by XericDesign** [sparkle-project/Sparkle#2302]
How can I hide the Version History button which seems just point to the html file that a normal update would show?

**Comment by zorgiepoo** [comment]
Please read [Full release notes](https://sparkle-project.org/documentation/publishing/#full-release-notes) first.

The full release notes is useful for users viewing your app's version history if there are no new updates available.

Because this is generally useful/helpful, this is the first request for hiding the functionality. This could be done as a delegate addition if you don't want to provide full release notes to the user however.

**Comment by zorgiepoo** [comment]
I'm adding a delegate API for this in https://github.com/sparkle-project/Sparkle/pull/2303

`- (BOOL)standardUserDriverShouldShowVersionHistoryForAppcastItem:(SUAppcastItem *)item;`
