### ISSUE TITLE
bundled executables don't have sandbox enabled

### ISSUE THREAD

**Issue by castdrian** [sparkle-project/Sparkle#2599]
## Summary

sparkle framework fails app store connect verification due to missing sandboxing for its bundled executables
![ishare-1721493866](https://github.com/user-attachments/assets/d99a925b-b971-4172-92bb-02f49fc3bd22)

I of course don't actually use sparkle in the app store build, but the framework is still bundled into the application

## Possible Fix

enable the app sandbox for all bundled executables

## Version

2.6.4

**Comment by zorgiepoo** [comment]
> I of course don't actually use sparkle in the app store build, but the framework is still bundled into the application

Developers do not bundle Sparkle for App Store builds.

**Comment by castdrian** [comment]
Developers do indeed bundle Sparkle for App Store builds.

**Comment by zorgiepoo** [comment]
I'm half-certain your app will be rejected if you include Sparkle in your app even if you get past these issues. It's not advised and most if not all apps do not do it. Plus you are bundling a framework you don't need for an App Store build, so it's also a waste.

Sparkle has never been fully sandboxed and developers have been shipping App Store and Sparkle builds side-by-side since 2011 or whenever the App Store came out for macOS.
