### ISSUE TITLE
System font greater than 13pt for SUStatus.xib

### ISSUE THREAD

**Issue by ChrisW698** [sparkle-project/Sparkle#2613]
We’ve received a number of user reports concerning the Sparkle update progress dialog, where the ‘x MB of x MB’ text appears larger than the System Regular 13 font size, causing the download progress count to be truncated. As shown in the attached screenshot, it seems that users are increasing the system-wide font size beyond System Regular 13 using TinkerTool, which is leading to this issue.
<img width="512" alt="Sparkle-TechToolPro" src="https://github.com/user-attachments/assets/a6d56212-ad43-4c2f-9a3a-9c8714d9ffd1">

**Comment by zorgiepoo** [comment]
This is an annoying Autolayout issue to enforce that the text field makes the window grow horizontally instead of wrapping or truncating in SUStatus.xib (SUStatusController also sets the font for the text field to be a monospaced digit system font with system font size).

After changing the system font you can set a breakpoint in `-[SPUStandardUserDriver showDownloadDidStartExtractingUpdate:]` to see how the status window looks like.

Note changing the system font with a non-system tool like TinkerTool is not a super supported/common path. However increasing the text field font size should technically work. Maybe @DivineDominion would have an idea on this. I don't want to subclass NSTextField.

**Comment by zorgiepoo** [comment]
Actually have a fix in #2614

**Comment by ChrisW698** [comment]
Thank you and greatly appreciated.

**Comment by DivineDominion** [comment]
@zorgiepoo I'm not that fast :D Happy that you found a solution already!
