### ISSUE TITLE
New icon(s)

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#347]
- Aqua bubbles are passé
- 10.10 introduces new look'n'feel of icons
- We don't have high-res original for the current icon

Also there's a problem that Autoupdate.app (formely finish_installation.app) may sometimes be user-visible, but Sparkle's icon is not immediately obvious or recognisable by an average (non-technical) user, so it causes confusion when it pops up.

We may need a new icon for the project, and perhaps a special version of the icon for the Autoupdate.app.

For the autoupdate the icon shouldn't be too branded, it should look generic, like a system utility, installer or such., so if user sees the Autoupdate.app somewhere they'll guess it's part of "plumbing" and not a user-facing app.

**Comment by Mecki78** [comment]
Why don't you just show the app icon instead? You can tell OS X which icon to show there, just as you can tell it which message to display (except for a fixed part that the system will always append to your message):

    const char * prompt = ...;
    const char * iconPath = ...;
    
    AuthorizationItem authItems[2] = {
    	{
    		.name = kAuthorizationEnvironmentPrompt,
    		.valueLength = strlen(prompt),
    		.value = (void *)prompt,
    		.flags = 0
    	}, {
    		.name = kAuthorizationEnvironmentIcon,
    		.valueLength = strlen(iconPath),
    		.value = (void *)iconPath,
    		.flags = 0
    	}
    };
    
    AuthorizationItemSet authEnvironment = {
    	.count = 2,
    	.items = authItems
    };
    
    AuthorizationItem sessionOwnerAuthItem = {
    	.name = kAuthorizationRightExecute,
    	.valueLength = 0,
    	.value = nil,
    	.flags = 0
    };
    
    AuthorizationRights rightsRequested = {
    	.count = 1,
    	.items = &sessionOwnerAuthItem
    };
    
    OSStatus err = AuthorizationCreate(
    	&rightsRequested, &authEnvironment,
    	kAuthorizationFlagPreAuthorize
    		| kAuthorizationFlagExtendRights
    		| kAuthorizationFlagInteractionAllowed,
    	NULL
    );

It's only important that the icon is **exactly** 32x32 pixels, the icon must be accessible by a system user that doesn't seem to be root (if you place it into a folder that only the current user has access to, it will not show on my system), the system doesn't like spaces in the path (no idea why!) and it doesn't like very long paths to begin with (not sure about the limit, stay below 128 chars) and ideally it should be a PNG (works best).

The easiest trick to make all this work: Load the Icon from the App as NSImage, scale it down to 32x32, write it as PNG to `/tmp` (e.g. /tmp/sparkle-icon-<rnd>.png` with `<rnd>` being some random ID to avoid collisions), show the dialog, once done, delete the icon from `/tmp`. This also circumvents all access rights, long paths and spaces in path problems and just works like a charm.

**Comment by 1024jp** [comment]
Hi, it seems that you are looking for a new icon for Sparkle and not yet decided.
And as a freeware icon designer, I probably can help you.

I made some drafts for Sparkle looking more modern, general and reticent.

<img src="https://cloud.githubusercontent.com/assets/1165044/14777924/0fc8f106-0b0b-11e6-8f08-dcadbea3d372.png" width="256"  alt="Sparkle"/> <img src="https://cloud.githubusercontent.com/assets/1165044/14777925/10dfbd7c-0b0b-11e6-8785-6054349a035c.png" width="256" alt="Sparkle 2" />


Added ✨ symbols to background to add a Sparkle-ly twist and inherit blue-color from the current Sparkle icon.
If you like one of these, I'll brush-up it in order to make it finish (I know, these were just roughly drawn).
Or if you have some image already in your head, please describe and I'll try drawing it.

FYI, you can see some of my previous works here:
https://dribbble.com/1024jp

When you already have a specific plan (or just you don't like my taste), just reject me.

**Comment by pornel** [comment]
Thank you @1024jp. The icon style is a better fit for modern OS X than what we have. The first icon has a generic look of a update app, so IMHO it'd be a good fit for the autoupdater.app.

I vaguely remember @jakepetroules was going to get in touch with a designer, but I don't know how that went.

**Comment by jakepetroules** [comment]
Wow, these look quite excellent! I did want to look into getting someone to design a new icon at some point but it looks like @1024jp has taken care of that for us. :) Would you care to submit a PR replacing Resources/Sparkle-Icon.psd with whatever original artwork you have for this?

We can discuss further there. Also, please do submit the original artwork under a permissive license embedded in the file metadata somewhere (I suggest [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)) so that we don't run into any legal problems down the line for anyone using Sparkle in their applications.

Thanks so much for taking the initiative here!

**Comment by pornel** [comment]
CC attribution would carry over to Sparkle.framework, and apps that use it, no? I think we need a license to distribute the icon on the [same terms](https://github.com/sparkle-project/Sparkle/blob/master/LICENSE) as the framework.

**Comment by 1024jp** [comment]
Hi, thank you for accepting my proposal.
So, I'm going to bring the circular arrows one to completion then make a pull-request (I may do it this weekend).

Regarding the license, both the Creative Commons and the MIT are acceptable for me. It's up to you guys (IMHO, the MIT license is enough if there is no special circumstances).  However anyway, since I'll make the graphic with Sketch.app, there is no way to embed license directly to the file as metadata. I'll probably just put a copyright/license sentence as a text object in the original image resource.

**Comment by jakepetroules** [comment]
Yes, I guess MIT would work even though it's rather odd to use for an image (as it explicitly mentions "software"). But I don't anticipate any problems. :)

**Comment by zorgiepoo** [comment]
Just to record the current places the icon is used:

1. The website (favicon, navbar, test app screenshot).
2. Authorization prompt (as mentioned before the icon can be customizable but it may not always be an available option).
3. Dock icon if the installer "takes too long" for non-automatic installs - also could be customizable, but I don't think it should be.
4. The Test Application, which is a user facing app but it doesn't really matter that much.

The new icon is indeed nicer :).
