### ISSUE TITLE
slow download from GitHub

### ISSUE THREAD

**Issue by mackuba** [sparkle-project/Sparkle#487]
I've noticed (not the first time, this happened many times before, possibly every time) that when I download a new version of my app locally to test a release, it downloads very, very slowly. The app is hosted on GitHub in the "releases" area (the URL actually redirects to `s3.amazonaws.com`). When I press "Install update", it starts quickly for a couple of seconds and then slows down to ~10-20 KB/s, so downloading 20 MB takes forever.

When I download the exact same URL on the same machine in the terminal with curl (even in parallel), after starting it instead speeds up gradually to ~150-200 KB/s. So it's not GitHub/S3, it's not my connection, it's rather how Sparkle or whatever it uses behind the scenes works with GitHub/S3 and/or my app. Chrome also downloads the file at around the same speed as curl.

I also tried uploading the same zip file to my own server and setting `SUFeedURL` to a URL on that server. I run "Install update" and this time it downloaded faster than with Chrome and curl before, at around 1-2 MB/s - the download was ready in less than 10 seconds. Again, same app, same machine, same configuration, same moment.

Any idea what's going on here?...

(Here's the link in question: https://github.com/hivewallet/hive-mac/releases/download/1.4.1/Hive-1.4.1s.zip)

**Comment by jsuder** [comment]
Oh, and this is on Mavericks and with Sparkle 1.8.

**Comment by jsuder** [comment]
It seems that `NSURLDownload` is the problem here - I've created a fresh new OSX app that has absolutely nothing in it except this:

```objc
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    NSString *url = @"https://github.com/hivewallet/hive-mac/releases/download/1.4.1/Hive-1.4.1s.zip";
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:url]];
    _total = 0;
    _download = [[NSURLDownload alloc] initWithRequest:request delegate:self];
}

- (void)download:(NSURLDownload *)__unused download didReceiveDataOfLength:(NSUInteger)length {
    _total += length;
    NSLog(@"+%ld => %ld", length, _total);
}
```

and it downloads the file in pieces of 9000 bytes... In the same time, curl or wget download the same file at about 400 KB/s.

Someone wrote something that it might be about the redirect, but if I paste the final URL instead it works the same.

Too bad I can't debug NSURLDownload now... :)

**Comment by pornel** [comment]
Thanks for checking this. I'm not sure how we can fix this :/

**Comment by jsuder** [comment]
I've asked GitHub if they know something, and I'll file a radar too.

BTW, the delta updates is something that is still recommended and supported, right? Or is this perhaps something new? I haven't tried it before... But it looks like it can bring the size down to ~3 MB, so that would make this problem much less serious.

**Comment by Kapeli** [comment]
For what it's worth... I've seen a similar issue while downloading using NSURLDownload from http://search.maven.org/. Switching from NSURLDownload to AFNetworking fixed things. I haven't investigated the issue further so no idea what's going on.

**Comment by jsuder** [comment]
I'm not seeing the same behavior on my other machine with Yosemite, so they might have fixed this. I'll know for sure after I update OS X on the MBA, which I'm planning to do in a few weeks.

**Comment by jsuder** [comment]
No, sorry, still there, I guess it just doesn't happen every time.

**Comment by zorgiepoo** [comment]
we don't use NSURLDownload anymore.
