### ISSUE TITLE
Install on Ubuntu?

### ISSUE THREAD

**Issue by pychen** [sparkle-project/Sparkle#496]
Hi,

First, thank you for this wonderful project.  I'm trying to install this on Ubuntu 14.04, and I'm getting the following error:

root@flex2:~/Sparkle# make
rm -f Sparkle/en.lproj/Sparkle.strings
genstrings -o Sparkle/en.lproj -s SULocalizedString Sparkle/*.m Sparkle/*.h
/bin/sh: 1: genstrings: not found
make: *** [localizable-strings] Error 127

and,

root@flex2:~/Sparkle# make release
xcodebuild -scheme Distribution -configuration Release -derivedDataPath "/Sparkle.eVFI2z" build
/bin/sh: 1: xcodebuild: not found
make: *** [release] Error 127

Can you please advise what I'm doing wrong?  Thank you in advance for all your help.

Cheers,
Peter

**Comment by balthisar** [comment]
Apparently you don't have the Mac OS X executables `genstrings` and `xcodebuild` on your Ubuntu system.

If you've managed to install GnuStep then maybe you'll have some luck, but given that you can't read the simplest output, I'm guessing that perhaps you're using the wrong repository for the wrong project, since this one will be absolutely no use to you on Ubuntu.

Can any of us help you find what you're really looking for?

**Comment by pychen** [comment]
Sorry, I started a new gig, and all they left me with on this is the following instructions:

# git clone https://github.com/sparkle-project/Sparkle.git
# cd Sparkle
# make

They use this app on an MacOS app, and I am suppose to use it to sign the package.  I really appreciate the quick response and all the help.

**Comment by pornel** [comment]
Sorry, Sparkle is for Mac OS X only and will not work on Ubuntu at all.

**Comment by pychen** [comment]
Thank you for your help.
