### ISSUE TITLE
Use the System Profiling Feature to Limit the # of License Installs?

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#500]
I finally decided to distribute my OS X apps outside MAS and I was just thinking of a strategy to limit the number of installs a single license will validate for (say I want a license key to validate on 3 Macs max at a time, otherwise I'll make the license key fail). I'm using CocoaFob. 

I am what I am...a client side developer....an Objective-C developer. Working on my own server side solution from scratch isn't exactly feasible for me at this time (I'd rather be working on my next Cocoa app and I don't have the time to spare). Some of the online services that provide this type of solution are pretty expensive. 

I was just thinking about the System Profiling feature of Sparkle and perhaps modifying that feature to send the license key up when the user registers my app (and offering an 'unregister this mac' menu item). Before trying to experiment with that API myself, I figured I'd ask if anyone has successfully done this before (is it a bad idea)? A feature like this I think would be really empowering for Cocoa developers.

**Comment by grahammiln** [comment]
I am not aware of anyone using Sparkle in this way.

You can certainly insert additional information into the optional profiling performed by Sparkle. There are existing delegate methods to help with this.

You may find the existing server side code on the [System Profiling](https://github.com/sparkle-project/Sparkle/wiki/System-Profiling) page useful.

Be aware that if you are sending sensitive licensing information through Sparkle, be sure to use an SSL/TLS connection, `https://` rather than `http://`. This is because Sparkle uses the `GET` http method by default and both the URL and parameters will be logged in your server logs – and logs of proxies or devices along the way.
