### ISSUE TITLE
Add option to have multiple updates in a single appcast that can be selectively chosen

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#51]
_**livings124 (livings124)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/316247) on' 2009-01-12:*

I'm not sure if "Answers" or here is the best place to add feature
requests, so I'm guessing it's here.

It would be useful to have multiple updates listed in a single appcast
file, with some sort of key separating them. This would be similar to
how it works now with minimum version numbers.

For an example, I could have 2 updates, one with no key and one with the
key "beta". There would be some sort of method (delegate maybe?) to
specify all the valid keys (as an array most likely). If no keys are
specified, the update with the "beta" key would be ignored and only the
other would be considered. If one of the keys specified in the code is
"beta", however, both would be considered, and the one with the higher
version number would be used. This would simplify things greatly for
users that want to support optional updates for betas, etc.; it's easier
to maintain and feels less hacky than having multiple feeds that have to
be synchronized.

**Comment by zorgiepoo** [comment]
This is a long old issue.. But I like the original proposal here where an appcast item can provide a set of tags (or "channels" because Sparkle has prematurely decided to use "tags" for something else now). By default, non-default channels would be ignored.

The posets and paid case I feel can be solved independently by #329 for specifying a version point where an update became a paid or major one. I don't think this feature should be related to offering paid upgrades, but rather should be for beta or nightly, or even demo channels.

The `-bestValidUpdateInAppcast:` delegate method has been almost forever buggy and slightly painful to support. It's likely difficult to use, and likely misused. And most importantly it requires developers implementing it before shipping an update they've already shipped, and is less friendly to external updaters.
