### ISSUE TITLE
-appCachePath can't use NSTemporaryDirectory() as fail-safe

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#613]
https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUHost.m#L65

See [this story](http://rickfillion.tumblr.com/post/110370590958/1password-update-failures) as a reason why we can't extract updates to a temporary directory. Does anyone know how likely it would be for `NSSearchPathForDirectoriesInDomains` to fail? If we think the cache lookup can reasonably fail, we could use an application support directory as a fail-safe, like Sparkle used to use a while back ago.

We should probably never assume -appCachePath returns non-nil as well.

**Comment by pornel** [comment]
Sparkle used to use App Support directory, but failed installations were leaving files behind, causing garbage to accumulate.

The caches directory has no guarantees either.

Regardless of temporary storage, the corruption could be prevented by moving verification to a later stage in the process (we need to do that for sandboxing anyway).

**Comment by zorgiepoo** [comment]
> Sparkle used to use App Support directory, but failed installations were leaving files behind, causing garbage to accumulate.

What does this mean? That files were left there without being removed later by Sparkle? This is not worse than the System randomly deleting some files.

> The caches directory has no guarantees either.

App support, caches, and temporary directory are *definitely* on different levels. Notably, the system won't delete files from Caches or App Support. For App Support, Spotlight and Time Machine will pick up files there. The temporary directory is completely unreliable for long term storage in our current case however.

> Regardless of temporary storage, the corruption could be prevented by moving verification to a later stage in the process (we need to do that for sandboxing anyway).

Perhaps. I was under the impression we had to move it to a separate process, not necessarily do the validation later. Regardless, for now, we should just avoid the temp directory for this bit of code.

**Comment by pornel** [comment]
I don't know how common is that Caches is unavailable, but I guess very rare. Also, I wouldn't be surprised if app support was unavailable at the same time too (e.g. if a special user without ~/Library runs the update?). 

So the problem is real, but happens in very narrow circumstances (caches unavailable + files left for long enough for cleanup to kick in), and just switching to app support may not be enough (it may also be unavailable, and proper use would require writing cleanup of files potentially left by a killed processes, while also ensuring it's not deleting files used by Sparkle in another instance of the same app).
 
If you think tmp is really really unacceptably bad, then I suggest aborting update completely instead of falling back to an alternative cache/tmp location.

But I'd leave it, and focus on moving verification step (which is difficult, but needed anyway).

**Comment by zorgiepoo** [comment]
Yeah, the fall back to tmp is probably rare. Especially, since `NSSearchPathForDirectoriesInDomains` can return a directory that doesn't exist yet.

Application Support and Caches directory are almost no different in terms of files being left around and needing cleanup. I've realized now that a user can install a 3rd party tool that cleans up caches - which makes me wonder, can such a user run into issue described in the story above?

I suppose what you're suggesting is that there shouldn't be any delay between a successful extraction/validation and installation. I'm not sure if this is "needed" even for sandboxing but it does sound like an ideal way of doing it.

**Comment by pornel** [comment]
> I suppose what you're suggesting is that there shouldn't be any delay between a successful extraction/validation and installation. 

Yes.

> I'm not sure if this is "needed" even for sandboxing but it does sound like an ideal way of doing it.

Sorry I wasn't clear. For sandboxing of course the delay doesn't matter. What matters is that the host can't be trusted to verify the download.

So moving download verification to a later stage in the process would help both use cases — the installation would become a one unit of work, which both removes the delay and makes it easier to encapsulate in a sandbox.
