### ISSUE TITLE
We have a sponsor

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#642]
Heads up everyone, we've got a sponsor: @maxcdn. I'll add links to the readme and pages soon.

This means the project will have some budget for things like commissioning a design, hosting, private jets, etc.

**Comment by grahammiln** [comment]
What is the sponsor requiring of the project and community?

**Comment by pornel** [comment]
It's a brand promotion on the project's pages. We ensure it's tasteful and unobtrusive. 

Sparkle's codebase is off limits and that is guaranteed to stay "white label" as always.

**Comment by jakepetroules** [comment]
Maybe we can use this bug report to allow the community to vote on and/or suggest some ideas for use of the budget?

**Comment by kainjow** [comment]
Someone should be sponsored to clean up the large list of issues... :)

**Comment by zorgiepoo** [comment]
How about a ssl certificate (https) for the main Sparkle website?

**Comment by jakepetroules** [comment]
Save the sponsorship funds for product-enhancing one time purchases rather than ongoing infrastructure/operating costs.

I'll take care of the latter (domains/SSL/hosting) - the only thing I don't really want to do, or have the time for, is set up all the automatic Jekyll deployment on push, etc., that GitHub Pages provides us. Any ideas for cost effective hosting providers which would simplify that process would be welcome.
