### ISSUE TITLE
What are the limitations when Sandboxed?

### ISSUE THREAD

**Issue by clausjoergensen** [sparkle-project/Sparkle#673]
I keep reading that Sandboxed apps aren't supported. Yet today, with the 1.11 version of Sparkle I successfully updated a code-signed app with sandboxing, using Sparkle via. HockeyApp (HTTPS of course)

Is the limitations somehow tied to auto-updating (without user interaction), or content updating (in the sandbox)? I know of Kent Sutherland's XPC branch, but I currently don't see the need for it.

**Comment by pornel** [comment]
The purpose of Sandboxing is to limit permissions the app needs to minimum, so that a compromised application can't do much damage.

However, for the app to update itself it needs a permission to install and run new executables, which is pretty much the maximum permission you can give it, which completely defeats the purpose of sandboxing. 

If your app has permission to replace apps in the system, then regardless of Sparkle, an attacker that can exploit that app can also install malware apps in the system.

As far as I know all existing forks/branches of Sparkle with XPC support offer no security. They pretend to have some security by limiting what the host app can do, but they have a priviledged XPC helper that will do anything that it's told. So if the host app is compromised, the attacker can tell the XPC helper to install malware, and the XPC helper will do it.

By "not supporting" Sandboxing we mean that we haven't developed a secure version of the XPC helper that would independently and securely verify all code it's told to install.

When we support sandboxing, we'll support it in a way that allows the host app to keep minimal privileges (i.e. no privilege to replace apps), and the XPC helper with strong security that only installs updates signed by the developer, rather than whatever it's told to.
