### ISSUE TITLE
Updating LaunchServices db

### ISSUE THREAD

**Issue by bryanc-nz** [sparkle-project/Sparkle#749]
I'm new to using Sparkle and maybe this is a newbie question.

After using Sparkle to update my app the Finder still displays LS info for the previous version. I double checked the new version info.plist and all looks good.

Corrected eventually using by OnyX to rebuild the LSDatabase.

Am I missing a sparkle key that should have done this automatically?

Thanks in advance
Bryan

**Comment by pornel** [comment]
We've been struggling with this for a while. #508 #509

**Comment by zorgiepoo** [comment]
We run `touch` / `utimes()` on the update now (since 1.12.0?), which I'd like to think should update LS.

Finder being updated could be a different matter. If you're running OS X 10.11, see issue #645. (*supposedly* it has been fixed in Apple internally but I haven't seen it been applied to a production release yet).

**Comment by bryanc-nz** [comment]
OS X 10.11.3

Thanks - just did a couple of tests
I have version 1.1.1 of my software installed
Downloaded from web server  and unzipped version 1.1.0
Finder shows it as version 1.1.1 (should display 1.1.0)
Relaunch Finder - version is now correct at 1.1.0

Update to 1.1.1 with Sparkle
Finder shows version 1.1.0
Relaunch Finder - version is now correct at 1.1.1

Conclusion - its a Finder bug and occurs independently of Sparkle

Thanks for the help and sorry for the noise
B
