### ISSUE TITLE
Unexpected behavior when product name changes

### ISSUE THREAD

**Issue by insidegui** [sparkle-project/Sparkle#782]
I have an app which is changing It's name from one version to the other (had to change It's name because of trademark issues). I renamed the app in Xcode, changed the product name but the bundle identifier is still the same.

While testing the Sparkle update locally, the update did download and install correctly, but Sparkle renamed the 'new app' to the old product name and didn't automatically relaunch It.

Is this the expected behavior when the product name changes?

I know this is an edge case, but since Sparkle is used a lot I would expect It to handle It a little bit better.

**Comment by zorgiepoo** [comment]
Preserving the old app name is expected behavior because the user can change the app name to whatever they want and we have to respect that.

We do have a compile setting for using the `CFBundleName` key as the app name when installing: https://github.com/sparkle-project/Sparkle/blob/master/Configurations/ConfigCommon.xcconfig#L12 -- this appears to use the `CFBundleName` from the currently installed app.

Failing to automatically relaunch the app is not expected behavior though, but not something I've been able to reproduce on my end.
