### ISSUE TITLE
"Switch" between branches back and forth?

### ISSUE THREAD

**Issue by mthielemann** [sparkle-project/Sparkle#791]
Hi,

I want to let the user choose between a stable and a pre-release branch. This works quite good but currently it is just possible to switch from the stable branch (with a slower build number) to the beta branch (with a higher build number). If the user decides to switch back from the beta to the stable branch it would be great if sparkle would offer the latest stable version even if the user has the beta version (with the higher build number) installed. Currently the user would have to manually reinstall the latest stable version. Is there any way to achieve this using Sparkle?

Thanks,
Marc

**Comment by jkbullard** [comment]
I don't think it is possible without patching Sparkle. At least not with Sparkle 1.5b6. Perhaps the prohibition against downgrades has been relaxed with newer versions, but allowing downgrades is a **bad idea** unless there are sufficient safeguards in place to avoid man-in-the-middle (MITM) attacks.

This is a security issue because the purpose of the prohibition against downgrades is to stop a MITM attack from enticing someone to downgrade to a version of the app that has security vulnerabilities that are known to the attacker. 

That said, [Tunnelblick](https://tunnelblick.net) allows such beta/stable switching. Because Tunnelblick tries to defend itself against "state level" MITM attacks, https: and digitally-signed update binaries are not sufficient for us, but they may be enough for you. Tunnelblick tries to avoid MITM attacks not only by using https: in all URLs (appcast, update notes, and update binaries) and requiring DSA signatures on the update binary, but also by requiring DSA signatures on appcasts and release notes (which is done via patches to Sparkle).

**Comment by zorgiepoo** [comment]
Downgrades should still be prohibited.

I have pushed beta updates with the aim of pushing a higher stable build in the future so this hasn't been much of a thought for me personally. That and users may not want to be prompted for downloading an older (even if stable) version.

**Comment by pornel** [comment]
Currently Sparkle won't ever downgrade, and that's by design.

I suppose you could hack it by implementing `versionComparatorForUpdater:` delegate method to say that a stable version is higher than a beta version when user opted out of betas.

**Comment by zorgiepoo** [comment]
Well you'd have to also look at `SPARKLE_AUTOMATED_DOWNGRADES` because the installer does a downgrade check for normal app updates, and custom version comparators don't apply there.
