### ISSUE TITLE
Invalid Argument from BinaryDelta

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#810]
I'm getting an Invalid Argument error from the BinaryDelta on the db in my app, but its inconsistent (sometimes it actually works):

Generating delta...
✏️  Updated /Contents/Info.plist
✏️  Updated /Contents/Resources/Main.storyboardc/Info.plist
BinaryDelta: ../Builds/Dev.app/Contents/Resources/db.sqlite: Invalid argument

I run two different BinaryDelta's concurrently (background process) for two outdated apps to help speed up delta generations. Is it not possible to run BinaryDelta concurrently maybe? It looks like another user had this issue years ago, but it wasn't resolved:

https://answers.launchpad.net/sparkle/+question/108082

**Comment by pornel** [comment]
I've checked, and we're using temporary files with unique random names, so I don't see how two processes could interfere with each other.

The string "Invalid argument" isn't anywhere in Sparkle itself, so it'd have to come from system/external error.

**Comment by ivankslalom** [comment]
I'm also working on this.  Parallel builds seem to work fine. I've traced the issue down to the bsdiff.c.  
Specifically 

if (((fd = open(argv[1], O_RDONLY, 0)) < 0)
        || ((oldsize = lseek(fd, 0, SEEK_END)) == -1)
        || ((old = malloc(oldsize + 1)) == NULL)
        || (lseek(fd, 0, SEEK_SET) != 0)        
        || (read(fd, old, oldsize) != oldsize)
        || (close(fd) == -1))
        err(1,"%s", argv[1]);

If I comment this piece of the code out I get the error below.  The file it's failing on is roughly 2.2 GB.  Other builds where the only difference is the database size (~100 MB) works fine as do parallel builds.

BinaryDelta(709,0x7000005b2000) malloc: *** mach_vm_map(size=1125881621700608) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
BinaryDelta: BinaryDelta: BinaryDelta: Cannot allocate memory

**Comment by zorgiepoo** [comment]
Could you specify what part of code that you've pasted that you are commenting out exactly? Some of those conditions in the `if()` initialize variables that would otherwise be un-initialized or incorrect. Altering or debugging bsdiff is really not something I'd look forward to :/.

"Invalid argument" does sound like some sort of C standard library error, or something. But if you don't see something like "mmap: <error>", then I'm less likely to believe the error is coming from our mmap call, as was the case in the thread that was linked.

**Comment by mdhari** [comment]
Its the if statement starting at line 147:
https://github.com/sparkle-project/Sparkle/blob/master/Vendor/bsdiff/bsdiff.c

**Comment by zorgiepoo** [comment]
Yes, commenting that line will break the program and leave variables un-initialized. I don't see how it'd help figuring out what's actually wrong.

**Comment by ivankslalom** [comment]
You're correct, it did have some unintended consequences downstream.  We prematurely reported what we had at the end of our day during our debug session.  We were glad to even have found the problem area.  We'll continue testing today and let you know of the progress.  For now my test is the following.  May work but some safety check risks?

fd = open(argv[1], O_RDONLY, 0);
    oldsize = lseek(fd, 0, SEEK_END);
    old = malloc(oldsize + 1);
    
//    /* Allocate oldsize + 1 bytes instead of oldsize bytes to ensure
//        that we never try to malloc(0) and get a NULL pointer */
//    if (((fd = open(argv[1], O_RDONLY, 0)) < 0)
//        || ((oldsize = lseek(fd, 0, SEEK_END)) == -1)
//        || ((old = malloc(oldsize + 1)) == NULL)
//        || (lseek(fd, 0, SEEK_SET) != 0)
//        || (read(fd, old, oldsize) != oldsize)
//        || (close(fd) == -1))
//        err(1,"%s", argv[1]);

    if (((I = malloc((oldsize + 1) * sizeof(off_t))) == NULL) ||
        ((V = malloc((oldsize + 1) * sizeof(off_t))) == NULL))
        err(1, NULL);

    /* Do a suffix sort on the old file. */
    I[0] = oldsize; sais(old, I+1, oldsize);

    free(V);

    fd = open(argv[2], O_RDONLY, 0);
    newsize = lseek(fd, 0, SEEK_END);
    new = malloc(newsize + 1);
    
    /* Allocate newsize + 1 bytes instead of newsize bytes to ensure
        that we never try to malloc(0) and get a NULL pointer */
//    if (((fd = open(argv[2], O_RDONLY, 0)) < 0) ||
//        ((newsize = lseek(fd, 0, SEEK_END)) == -1) ||
//        ((new = malloc(newsize + 1)) == NULL) ||
//        (lseek(fd, 0, SEEK_SET) != 0) ||
//        (read(fd, new, newsize) != newsize) ||
//        (close(fd) == -1))
//        err(1,"%s", argv[2]);

**Comment by ivankslalom** [comment]
Leaving out the error checks but running each command generates a patch file but when applied errors in applying with "corrupt patch file"

    fd = open(argv[1], O_RDONLY, 0);
    oldsize = lseek(fd, 0, SEEK_END);
    old = malloc(oldsize + 1);
    lseek(fd, 0, SEEK_SET);
    read(fd, old, oldsize);
    close(fd);

//    if (((fd = open(argv[1], O_RDONLY, 0)) < 0)
//        || ((oldsize = lseek(fd, 0, SEEK_END)) == -1)
//        || ((old = malloc(oldsize + 1)) == NULL)
//        || (lseek(fd, 0, SEEK_SET) != 0)
//        || (read(fd, old, oldsize) != oldsize)
//        || (close(fd) == -1))
//        err(1,"%s", argv[1]);

**Comment by ivankslalom** [comment]
Maybe relevant forum thread (#3 bsdiff exited not being able to allocate memory...)
http://www.donationcoder.com/forum/index.php?topic=34716.0

Is there any fork for Sparkle using xdelta?

**Comment by zorgiepoo** [comment]
You say malloc is failing, but your screenshot shows otherwise (or how would have it been able to break on `read()`?). I don't trust Xcode's debugger being able to give a good representation of the `old` pointer.

Diff'ing gigantic files should really be avoided in general, and bsdiff is also very inefficient at it. There probably isn't any fork using xdelta. I would be curious if the xdelta tools work well for your file though. Although xdelta is designed more as a library with more options, its API documentation is not the best so implementing that may not be trivial - and either utility could be bound to have unknown issues..

**Comment by ivankslalom** [comment]
Xcode for some reason jumps up and down to read and back to the malloc however the last line before it gets to error is the malloc.  Other files actually will print out values in old.  The Sqlite file stays NULL.  Suspiciously it's just above 2GB whereas this was working before when it was under.  

The gigantic files are the very reason why we wanted to leverage Sparkle/deltas.  

Maybe I'll give xdelta a go for a limited time.

**Comment by zorgiepoo** [comment]
> Xcode for some reason jumps up and down to read and back to the malloc however the last line before it gets to error is the malloc. Other files actually will print out values in old

malloc returns you a block of data that isn't zero'ed and could be pointing to random data. Since old is a `u_char *` Xcode is trying to interpret it as a string which is wrong and unreliable. It could be that malloc is failing but I'm still unconvinced. If it was the case it was failing, I'm not sure if there's much you can do about that though.

deltas should work well for big bundles sure, but working with large individual files that aren't static is less ideal.

@mdhari I see you posted on xdelta's issues about compiling it. You might have better luck with [this repo](https://github.com/jmacd/xdelta-gpl).

**Comment by zorgiepoo** [comment]
It just hit me hard that parallel builds implies needing to use >= 2x amount of memory usage.

**Comment by ivankslalom** [comment]
Yeah we were going to test the limits of that. We have it running on a 64 GB RAM box.

On May 13, 2016, at 7:36 PM, Mayur Pawashe <notifications@github.com<mailto:notifications@github.com>> wrote:


It just hit me hard that parallel builds implies needing to use >= 2x amount of memory usage.

-

**Comment by ivankslalom** [comment]
we also spent a bit more time breaking out the if conditions and the exact error comes from the read call.  It returns -1 and the errno is set with a value of 22 which is where "invalid argument" comes from.  The old still seems to point to a null value per the screenshot but as you say may not be accurate.

**Comment by mdhari** [comment]
If you comment the `(read(fd, old, oldsize) != oldsize) ||` and  `(read(fd, new, newsize) != newsize) ||` in bsdiff.c, the code continues but the patch generated is corrupted. 

Maybe this was a mechanism to short circuit the program because it doesn't support diffing files greater than 2^32 bytes?

**Comment by mdhari** [comment]
@zorgiepoo Thanks for the tip btw, I was able to install that the 3.1.0 xdelta3 beta version

The patching process on the 2.15 GB to 2.16 GB file works in reasonable time, but it looks like xdelta doesn't support a single patch file for a directory.

https://github.com/jmacd/xdelta/issues/21

Just out of curiosity, have you worked on integrating xdelta within Sparkle before?

**Comment by zorgiepoo** [comment]
> we also spent a bit more time breaking out the if conditions and the exact error comes from the read call. It returns -1 and the errno is set with a value of 22 which is where "invalid argument" comes from

That is interesting but I also find that kind of strange and don't immediately see what's wrong with the code.

> The old still seems to point to a null value per the screenshot but as you say may not be accurate.

I think you may be misinterpreting the screenshot, which all it's saying is the first byte to the block is a zero. It's not giving a pointer representation of `old` because Xcode thinks its contents is a string, but it's not, so it's not giving you any useful representation.

> If you comment the (read(fd, old, oldsize) != oldsize) || and (read(fd, new, newsize) != newsize) || in bsdiff.c, the code continues but the patch generated is corrupted.

This is naturally expected because these calls read in the data from the files into memory, as well as make sure the correct number of bytes have been read.

> The patching process on the 2.15 GB to 2.16 GB file works in reasonable time.

I'm curious if the patch file size that was generated worked favorably too!

> .. but it looks like xdelta doesn't support a single patch file for a directory.

Neither does bsdiff; that is as I expected. We'd want to integrate it in BinaryDelta if we decide to support it. I briefly looked at it but didn't get very far. I first glanced at using the API directly, but now I'm thinking that making a target to build & bundle the tool may be a better idea. We don't want to do any compression or integrity test when creating/applying the patch as well because BinaryDelta already handles that.

**Comment by mdhari** [comment]
Got bsdiff and bspatch to work finally with the large files. It took a couple of beers to understand the actual issue. 

The read function needed to be buffered. So I just added a readall function that I found from here: http://www.unix.com/programming/177585-maximum-buffer-size-read.html

But I modified it to understand the fact that there is a 2^32 limit on the number of bytes that can be read in one call (2147483647). This code can obviously be cleaned up. 

```
ssize_t readall(int fd, char *buf, size_t bytes)
{
    ssize_t bytes_read = 0;
    ssize_t n=0;
    
    do {
        if ((n = read(fd,
                      &buf[bytes_read],
                      bytes - bytes_read > 2147483647 ? 2147483647:bytes - bytes_read)) == -1)
        {
            if (errno == EINTR)  // resume on INTR
                continue;
            else
                return -1;
        }
        if (n == 0)
            return bytes_read;
        bytes_read += n;
    } while (bytes_read < bytes);
    return bytes_read;
}
```
So I replaced the read() with readall() and the patch file gets generated. I had to write similar functions for the read and write in the bspatch code.

But it works, the 220.2 MB applied to the 2.15 GB file and produced the 2.16 GB file cleanly.

**Comment by zorgiepoo** [comment]
Good find! Although, I am still puzzled about the "Invalid Argument" error from before.

I think we'd be better off using the higher level `FILE *` functions instead.

**Comment by mdhari** [comment]
I did see that fread and fwrite did not have this strange limit by the way. Maybe you could replace the read and write with those functions. 

Closing as my short term solution works for now.

**Comment by zorgiepoo** [comment]
@mdhari Yeah, I have submitted a PR at #811 for doing just that (and some other fixes). If you want to give that a go, feel free.
