### ISSUE TITLE
Inappropriate insecure update error

### ISSUE THREAD

**Issue by iosdeveloper** [sparkle-project/Sparkle#820]
If instead of the `<enclosure>` tag I use `<link>` as documented [here](https://sparkle-project.org/documentation/publishing/#downloading-from-a-web-site) for an app that is not code signed, showing the insecure update error (https://github.com/sparkle-project/Sparkle/blob/e2c60be8059602c0c73bea0ce3d928539db7ae55/Sparkle/SUUpdater.m#L134-L136) seems inappropriate.
![screenshot](https://cloud.githubusercontent.com/assets/655921/15974009/95bf59d0-2f46-11e6-8d44-5dc2cfa74d8d.png)

**Comment by pornel** [comment]
Yes, indeed. This check assumes there's something to install.

**Comment by pornel** [comment]
I'm not sure if we want to add extra complexity to the check here, as we'd first have to download and analyse the feed to skip it in case of link-only feed. And then you'd get a nasty surprise if you decided to send enclosures later.

So I think in this case I recommend adding a DSA key file. It doesn't even have to be a valid key (in case you don't ever want to allow autoupdates). 

To silence the warning add `SUPublicDSAKeyKey` to Info.plist that points to a plain text file that exists in the bundle.

**Comment by iosdeveloper** [comment]
@pornel Adding the `SUPublicDSAKey` to Info.plist works. Thanks for the pointer!

**Comment by iosdeveloper** [comment]
@pornel It worked, however updates can't be installed now.
<img width="532" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/655921/16310647/a5dfcecc-396d-11e6-8f01-b5a310056da2.png">
You can install v2b5 and it'll prompt you to update to v2b6: https://github.com/matryer/bitbar/releases
Here are the logs:

> 6/23/16 10:22:35.599 AM BitBar[712]: Sparkle: Extracting using '/usr/bin/ditto' '-x' '-k' '-' < '/Users/user/Library/Caches/com.matryer.BitBar/org.sparkle-project.Sparkle/BitBar 2.0.0-beta6/BitBar-v2.0.0-beta6.zip' '/Users/macg/Library/Caches/com.matryer.BitBar/org.sparkle-project.Sparkle/BitBar 2.0.0-beta6'
> 6/23/16 10:22:36.965 AM BitBar[712]: Sparkle: There is no DSA signature to check
> 6/23/16 10:22:36.965 AM BitBar[712]: Sparkle: DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the public key doesn't match the signature. The update will be rejected.
> 6/23/16 10:22:38.961 AM BitBar[712]: Sparkle: Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed. (URL (null))

**Comment by pornel** [comment]
Sorry, I've assumed you were using `<link>` and not `<enclosure>`, because you didn't use automatic updates.

I'll check what the code does.

**Comment by iosdeveloper** [comment]
@pornel I switched to `<enclosure>` after this issue was opened, sorry. Still looking to suppress the alert if the running app is not signed (i.e. during development).

**Comment by pornel** [comment]
You're hitting [this check](https://github.com/sparkle-project/Sparkle/blob/9944f2496c9627ab111eb43a5da68e430a7c0d63/Sparkle/SUBasicUpdateDriver.m#L324-L330). 

If the new version contains a DSA key, it needs to also have a valid DSA signature in the feed. This is a check to prevent accidentally locking yourself out from updates by shipping an app with an invalid key.

So in this case if you include a DSA key, also sign bundles with it.

**Comment by pornel** [comment]
So going back to your original problem, I don't ha

**Comment by iosdeveloper** [comment]
@pornel Release builds are signed, so it's not an issue there. During development the app is usually not signed, therefore the alert appears on launch *before* even attempting to install an update. I would be fine with an alert when attempting to install an update from an unsigned app.

**Comment by koralcem** [comment]
Came across this issue when looking for a similar thing myself; just a way to stop the errors during development. 

Had a question along those lines: What *precisely* is the reason the docs suggest putting the `SUUpdater` object in `MainMenu.xib`? Is it just to make sure it gets initialized and checks for an update as soon as the app is launched?

Because I tried the following: Removed `SUUpdater` from `MainMenu.xib` and added the following (what feels like) hack:
```objective-c
    int main(int argc, char *argv[])
    {
    #if RELEASE
        [SUUpdater sharedUpdater];
    #endif
    ...
```
This behaves as I would expect it. On a debug build the creation of the updater upon launch gets skipped. If I trigger an update check from the menu, which is hooked up to `checkForUpdates`, I still see the error (but that's fine at that point). On a release build we create the updater as the first thing, which checks for an update immediately, and I still see the error.

So my question is: Is there some technical/specific reason why the updater has to be in `MainMenu.xib`, besides early initialization? Do we lose anything if we do it programmatically like this?

**Comment by pornel** [comment]
I don't think it's necessary to use it in `MainMenu.xib` — it's just a way to use it without writing any code.

**Comment by zorgiepoo** [comment]
> So my question is: Is there some technical/specific reason why the updater has to be in MainMenu.xib, besides early initialization? Do we lose anything if we do it programmatically like this?

You will need to hook up the check for updates action, and write a small piece of glue code for the check for updates menu item validation. Otherwise, it's fine to use, and it doesn't have to be initialized early in `main()` - it could be initialized say when the application is finished launching.

I really don't like the nib based approach myself.

**Comment by koralcem** [comment]
Thanks for the info guys. If we're not shy of writing code, is `[SUUpdater sharedUpdater]` the right way to kick everything off, since it looks like it calls the appropriate initializations?

Also, @zorgiepoo I'm curious: Why do you say init shouldn't happen in `main()`?

**Comment by zorgiepoo** [comment]
> Thanks for the info guys. If we're not shy of writing code, is [SUUpdater sharedUpdater] the right way to kick everything off, since it looks like it calls the appropriate initializations?

`[[SUUpdater alloc] init]` may be a more direct approach - `-init` is what is invoked when SUUpdater is instantiated in a nib. I also like to avoid treating the updater as a singleton just for good hygiene sake.

> Also, @zorgiepoo I'm curious: Why do you say init shouldn't happen in main()?

First, generally Cocoa applications avoid altering `main()`. As for if it'll work fine, It may be fine, but I'm not sure. There is logic in the SUUpdater initialization to start its update cycle work during the *next* runloop cycle. This may be to prevent the updater showing any UI (eg: update permission prompt), too soon. Thus, I think it's a safer bet to start the updater later rather than earlier.
