### ISSUE TITLE
Keychain Support

### ISSUE THREAD

**Issue by DouglasCobb** [sparkle-project/Sparkle#888]
Have you guys thought about adding support for preserving keychain item access thought an update? Something like the parent application gives the update process access to the keychain items and then once the updater has finished it will give permission back to the updated application.

**Comment by zorgiepoo** [comment]
Does this pertain to authentication or something else in the update process? What benefit are you hoping to achieve? I don't think using keychain would be that appropriate with the authorization APIs.

**Comment by DouglasCobb** [comment]
Sorry I should have explained it better. I am actually asking for a feature.

My app creates keys and passwords and stores them in the keychain. My problem is that overtime I update the app the user is being prompted to allow the app to access those keychain items even tho they already had permission. This is because the keychain knows that the hash for the app has changed so it removes the permission. This is not a problem when using the app store because the App Store will update its permission so that it knows that the permissions on the apps keychain items is still valid. 

What I was thinking is that there could be a way for the main application to pass access to its keychain items to the updater application in the sparkle framework and once the application is done updating the updater would pass the access to those keychain items back to the main app.

That way the user wouldn't be prompted to allow access to those keychain items.

Did that make sense?

**Comment by zorgiepoo** [comment]
Yeah, I think this makes sense. But I think what you want is supposed to be achieved by [Apple's code signing](https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html) in general:

> Users appreciate code signing. After installing a new version of a code-signed app, a user is not bothered with alerts asking again for permission to access the keychain or similar resources. As long as the new version uses the same digital signature, OS X can treat the new app exactly as it treated the previous one.

You'd also want access to be preserved when the user may choose to update your app by visiting your app's website rather than going through Sparkle.

**Comment by jkbullard** [comment]
You need to digitally sign your app and the updated app. If you do, OS X will recognize that the updated app is from the same (trusted) source as the original app, and allow access to Keychain items as if it were the original app.

For this purpose, you don't need to use an Apple developer signing ID, you can use a private signing ID. For more info, see Apple's [Technical Note TN2206: OS X Code Signing In Depth](https://developer.apple.com/library/mac/technotes/tn2206/_index.html).

This is exactly what my app ([Tunnelblick](https://tunnelblick.net) does. We sign with an Apple developer ID so that users can just double-click the app (because of Gatekeeper) but before that we signed it with a private ID.

**Comment by DouglasCobb** [comment]
Thanks a lot guys! I am signing my app with a developer ID cert so that should work for me. You know in apples keychain documentation it specifically says that apple looks at the application hash to preserve access to items and doesn't mention signing at all. I guess I just didn't look at the right documentation. Thanks again
