### ISSUE TITLE
exception on 10.12

### ISSUE THREAD

**Issue by circleplus** [sparkle-project/Sparkle#898]
Our product has integrated with latest 1.14.0 release. And we have found on 10.12 (official release) an exception is periodically thrown, as seen below logs:

> Terminating app due to uncaught exception 'SUNoFeedURL', reason: 'You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!'
> terminating with uncaught exception of type NSException
> abort() called

This seems only happening on 10.12 as we've never seen this before, nor on 10.11 and prior OSX versions. The feed url is right inside user preference DB (in ~/Library/Preferences/). We have no clue why this might happen on 10.12, which might be a Mac Sierra bug.  We create a ticket here in case anyone run into it too and might have some insights. Thanks!

**Comment by zorgiepoo** [comment]
What is the output if you execute this on the command line (the plist file does not reflect the current user defaults state):
`defaults read <insert-bundle-identifier> SUFeedURL`

or if you invoke via code:
`[[NSUserDefaults standardUserDefaults] objectForKey:@"SUFeedURL"]`

I suspect you intentionally don't have the SUFeedURL key set in your app's Info.plist and don't implement the `-feedURLStringForUpdater:` delegate method.

**Comment by circleplus** [comment]
Thanks for your prompt reply.  defaults read is okay. The problem is it happened randomly and I myself couldn't reproduce it. We just received reports and logs.

However, yes, we don't have SUFeedURL key set in our app's info.plist, and we don't implement "feedURLStringForUpdater:" delegate method as well. We simply call "setFeedURL" on [SUUpdater sharedUpdater]. Like I said, this works all the time until 10.12.  But we recently just upgraded to 1.14.0, and I didn't see much change around that though.

**Comment by zorgiepoo** [comment]
Hm, not really sure. The only thing I can think of is if the user defaults are deleted, a `setFeedURL:` call is not invoked before the next update check, and an update check is done in the background or by the user. Personally I recommend the delegate method.

**Comment by circleplus** [comment]
Thanks for your suggestion. Using delegate method sounds great to me and I'll report back if that works - which means we don't receive any reports on 10.12.

**Comment by prasha6** [comment]
Yes, I have this same crash from users. Also, this crash happens only in 10.12. I have also been setting the setFeedURL on the SUUpdater.sharedUpdater.
These are some of my additional findings from the crash data:

1. All these Crashes happened on Mac OS 10.12
2. All these crashes happened pretty much at the launch of the application
3. Also, I see this method call in the callstack when the app crashed: [SUUpdater checkForUpdatesInBgReachabilityCheckWithDriver: ]

I think the delegate method should solve this problem. Looking at the sparkle source code, it is checked if the delegate returns any feedUrl, before throwing out the exception.
 @circleplus  please let me know if the delegate approach worked for you ?

**Comment by zorgiepoo** [comment]
I'm just going to continue the discussion over in this thread.

The delegate method is indeed better because the user can try to change your app's user defaults and the defaults persist. As long as the delegate is not nil at the time Sparkle is checking for updates, you should be good. So it's best to set the delegate (or feed url) as soon as possible after the updater is instantiated.

For example, I believe this case *could* cause a crash (assuming the updater is not being instantiated in a nib for simplicity):

```
SUUpdater *updater = [SUUpdater sharedUpdater]
dispatch_async(dispatch_get_main_queue(), ^{
    updater.delegate = ...
});
```

It's interesting this crash is only happening on 10.12 though. It sounds like it happens when Sparkle tries to check for an update in the background automatically near the application's launch.

**Comment by zorgiepoo** [comment]
Something to try with your current app:

1. Quit your app.
2. Execute `defaults delete app-bundle-identifier SUFeedURL` and `defaults delete app-bundle-identifier SULastCheckTime`
3. Launch your app. Does it crash?

**Comment by prasha6** [comment]
No it doesn't crash. SUFeedURL in fact gets its value after launching the application.

Also, I don't understand this: 

> For example, I believe this case could cause a crash (assuming the updater is not being instantiated in a nib for simplicity):


```
SUUpdater *updater = [SUUpdater sharedUpdater]
dispatch_async(dispatch_get_main_queue(), ^{
    updater.delegate = ...
});
```

**Comment by zorgiepoo** [comment]
> No it doesn't crash. SUFeedURL in fact gets its value after launching the application.

I presume a software update dialog showed up then after deleting those two defaults?

@prasha6 that sample code just demonstrates a case where the updater checks for an update automatically before the delegate (or feed URL) is set. The updater's initializer tries to schedule an update check at the next runloop cycle.

**Comment by prasha6** [comment]
> I presume a software update dialog showed up then after deleting those two defaults?

No, nothing showed up. I simply deleted them from command line, and read them back to ensure they are deleted.

> that sample code just demonstrates a case where the updater checks for an update automatically before the delegate (or feed URL) is set. The updater's initializer tries to schedule an update check at the next runloop cycle.

How to avoid the updater checking for updates automatically, before the delegate is set.
I am currently doing the following: Does it ensure the updates are checked only after the delegate is set ?
```
            this.Updater.Delegate = new UpdaterDelegate(update);
            this.Updater.AutomaticallyDownloadsUpdates = true;
            this.Updater.CheckForUpdatesInBackground();
```

**Comment by zorgiepoo** [comment]
```
No, nothing showed up. I simply deleted them from command line, and read them back to ensure they are deleted.
```

I guess in your case you may have automatic downloading enabled which may download updates silently. I would see if an exception is raised/logged anywhere, if you have sparkle trying to check for updates after removing the feed url key.

> How to avoid the updater checking for updates automatically, before the delegate is set.
I am currently doing the following: Does it ensure the updates are checked only after the delegate is set ?

I should first mention that this should be fine:

```
SUUpdater *updater = [SUUpdater sharedUpdater]
updater.delegate = ...
```
Because the delegate is set immediately after the updater is instantiated.

You can always disable `SUEnableAutomaticChecks` if that's suitable for your application: https://sparkle-project.org/documentation/customization/#infoplist-settings

**Comment by nfgrilo** [comment]
Hi!

Just quick follow-up, the we are also experiencing this crashing issue.

> I suspect you intentionally don't have the SUFeedURL key set in your app's Info.plist and don't implement the -feedURLStringForUpdater: delegate method.

All true! We are also setting the update URL via `setFeedURL:` instead (and only), and this issue only happens on macOS 10.12.

We will be shipping an update to our users on the following days, and will replace this `setFeedURL:` call by the suggested delegate method, so I can give feedback on this in a week on so!

Thank you,
Nuno

**Comment by prasha6** [comment]
Ok, So we have two things common in all of our crashes:

> 1. Crash happens only in 10.12
> 2. FeedURL was set programmatically like SUUpdater.SharedUpdater.FeedURL = someurl;

_The thing we need to understand is why did this crash not happen earlier, and why is it happening only in 10.12 ?_

Also, the only way I can support, that delegate approach would work fine would be - In Sparkle code, the return of the delegate method is checked before throwing this crash exception message. And, this is the only place that this exception message is thrown.


>     NSString *appcastString = [self.host objectForKey:SUFeedURLKey];
>     if ([self.delegate respondsToSelector:@selector(feedURLStringForUpdater:)])
>         appcastString = [self.delegate feedURLStringForUpdater:self];
>     if (!appcastString) // Can't find an appcast string!
>         [NSException raise:@"SUNoFeedURL" format:@"You must specify the URL of the appcast as the %@ key in either the Info.plist or the user defaults!", SUFeedURLKey];

_Apart from the above reasoning, I can't find why using the delegate approach would actually fix the crash ?_

Any suggestions are appreciated! Thanks.

**Comment by jkbullard** [comment]
If the sequence is:
 1. Start update checking
 2. Set feedURL

then the crash makes sense. The question is at what point is the feedURL set, compared to starting to check for updates?

My app is set up per the instructions from Sparkle 1.5b6:
 * the feedURL is set in application**Will**FinishLaunching
 * update checking is started in application**Did**FinishLaunching.

That seems to work (even on Sierra) but perhaps Sierra has optimized the application launch sequence such that the DidFinish notification is sent very shortly after the WillFinish notification, so a race condition occurs (depending on what else is done in the two notification handlers), making it possible for update checking to start before feedURL is set.

So I'm adding the delegate method to my application, just to make sure that can't happen.

**Comment by zorgiepoo** [comment]
> So I'm adding the delegate method to my application, just to make sure that can't happen.

Just make sure the delegate is set as soon as possible. If you're instantiating the updater in a nib, that means hooking up the IBOutlet. Some kind of out-of-order sequence seems likely but I'm unable to reproduce or reason about an unordinary one.

On another note, 1.15 (close to release) removes reachability checking and `-[SUUpdater checkForUpdatesInBgReachabilityCheckWithDriver: ]`, which should make the behavior more predictable (removing a background thread that was involved with that).

**Comment by zorgiepoo** [comment]
After looking into it a bit more, if you received crashes on 1.14.0, you should try 1.15 and follow the steps [here](https://github.com/sparkle-project/Sparkle/issues/898#issuecomment-257716806) to see if it's easier to reproduce.

Because 1.14.0 spawns a background thread which needs to synchronize with the main thread to retrieve the feed url (1.15 doesn't do this), it's not surprising that there is a race condition and that the exception is possible to occur on one system but not on another (in fact I've written a test app that crashes only sometimes on 10.10 in my VM but crashes consistently on my 10.12 machines).

If you currently use `setFeedURL:`..

1. Are you *always* invoking `setFeedURL:` *as soon as possible*? If you have a Cocoa application and are instantiating the updater in the nib where the application delegate is instantiated in, setting the feed url in `-awakeFromNib`, `-applicationWillFinishLaunching:`, `-applicationDidFinishLaunching:` should all be okay (they're in the same runloop cycle).
2. Does your app suppress the initial prompt to ask the user's permission if they want to check for updates automatically (or possibly make the permission prompt occur on first launch)? If your app does, it's more likely to get into this crash scenario, because otherwise the feed url could be set the first time your app is launched when no update checking is done in the background.

Mitigations:

1. Use the delegate method as mentioned above, but again, make sure the delegate is set *as soon as possible*. The delegate is better because users can change or remove your feed url via user defaults, which would also cause a crash.

2. Set a feed url in your app's Info.plist as a safe case.

**Comment by pornel** [comment]
Feel free to reopen if it still happens on 1.15 or 1.16.
