### ISSUE TITLE
Auto update not working every 1 hour

### ISSUE THREAD

**Issue by jakjothi** [sparkle-project/Sparkle#918]
I have integrated sparkle with my cocoa swift app, it works fine while initiate app check the updates and install

```swift
/// Sparkle updater rss feed uri
UserDefaults.standard.set(SparkleUpdateFeed[applicationEnvironment.lowercased()]!, forKey: "SUFeedURL")
self.suUpdater = SUUpdater.shared()
self.suUpdater?.delegate = self        
self.suUpdater?.automaticallyChecksForUpdates = true
self.suUpdater?.automaticallyDownloadsUpdates = true
self.suUpdater?.updateCheckInterval = 3600
self.suUpdater?.checkForUpdatesInBackground()
self.suUpdater?.installUpdatesIfAvailable()
self.suUpdater?.resetUpdateCycle()
```

Why it's not working every 1 hour and how can test it's working perfectly

**Comment by zorgiepoo** [comment]
Setting `SUFeedURL` user default manually is equivalent to using the `feedURL` property.

With that said, you should prefer to customize Sparkle [in your Info.plist](https://sparkle-project.org/documentation/customization/) instead (`SUEnableAutomaticChecks`, `SUFeedURL`, `SUScheduledCheckInterval`) since they won't be stored in your user defaults (unless you have a user change a setting). You may have to clear the user defaults though, if that's an option available to you..

You shouldn't use `installUpdatesIfAvailable()`

Invoking `checkForUpdatesInBackground()` is only necessary if you want Sparkle to check for updates right away after creating the updater. If you don't invoke it and automatic update checking is on (it's on by default), then Sparkle will check for updates when the update check interval arrives.

You probably don't want to call `resetUpdateCycle()` too, at least not early on in your application.

What do you mean by not working? If `automaticallyDownloadsUpdates` is enabled (again, this uses user defaults), then updates are downloaded in the background silently without the user noticing and will be installed when the application quits. If it's disabled (which is the default initially), then an update prompt will show up when the update check arrives instead.

**Comment by jakjothi** [comment]
@zorgiepoo thanks much, it works perfect.
