### ISSUE TITLE
Incorrect Read-Only Volume Error?

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#923]
I've had a handful of reports from users of my app who are seeing a message like this when they check for updates:

<img width="663" alt="screen shot 2016-11-21 at 11 28 23" src="https://cloud.githubusercontent.com/assets/926566/20497490/3a87cce6-afde-11e6-8bca-c98d9ca9d590.png">

The problem is that the app *IS* running from the Applications folder.

### What I've Tried:

To attempt to solve the issue for my customers, I've tried these things:

1. Had the customer verify that the app is running from the Applications folder on their built-in drive, not the Applications folder on a backup drive or cloned disk, etc.

2. Had the customer reboot.

3. Had the customer delete the app and download a fresh copy from my website.

### Impact:

So far, this issue appears to affect a very small number of users. I've had about 8 reports so far. There are thousands and thousands of people who are updating the app just fine. What's the next thing I should have these people do to diagnose the problem?

**Comment by zorgiepoo** [comment]
This sounds like it could be App Translocation / Gatekeeper randomization taking action in macOS 10.12

Basically, when you download an application and launch it, it is in a "translocated" state (for security reasons I'll skip mentioning) such that the system will translocate the application to a read-only mount. If the user *directly* moves the application elsewhere *using Finder*, the translocation flag in the quarantine extended file attribute will go away. In your particular case, I may be interested in *how* the user is moving the application into /Applications/

Apple has a way for developers to opt out of app translocation though. They want you to ship a dmg from your website, and codesign the disk image. Please see [step 0](https://sparkle-project.org/documentation/) in Sparkle's documentation for more details. I personally still find anything-not-dmg preferable for updates that go directly through Sparkle though.

And because of translocation if you really want to know where the application is running from, you shouldn't trust what Finder says. You could for example find the application in Activity Monitor, get information on it, and inspect the open file and ports.

**Comment by bdkjones** [comment]
Cool, that sounds promising. My users installed the app by unzipping it, then dragging it from Downloads to Applications.

[This article](http://lapcatsoftware.com/articles/app-translocation.html) seems to suggest there's an API for this new headache. Do you have a suggested approach for how Sparkle can deal with this? At the very least, it seems like this dialog should be updated with a more descriptive error message if translocating has occurred, as well as an option to copy the app to /Applications and nuke the bit that's causing the problem.

**Comment by zorgiepoo** [comment]
> Cool, that sounds promising. My users installed the app by unzipping it, then dragging it from Downloads to Applications.

I wonder if they're using Finder or an alternative perhaps.

> This article seems to suggest there's an API for this new headache. Do you have a suggested approach for how Sparkle can deal with this?

I haven't really looked into the new APIs, but generally I think Sparkle shouldn't deal with it. I was hoping Apple may provide an alternative way to opt out of translocation other than shipping a code signed dmg, but they have not (yet) (#832). We could possibly update the error message although from a normal user's point of view they probably won't know what translocation is anyway. I think copying the app outside may be out of Sparkle's scope; some people use LetsMove or write something on their own, others deal with the system behavior, others hope Apple will improve the installation experience.

To be clear, Apple doesn't want your application to be translocated at all which is why they provide an option for opting out -- shipping a code signed dmg.

**Comment by bdkjones** [comment]
Well, I definitely think Sparkle should be, at the very least, smart enough to inform the user that translocation has occurred.

Right now, this error message is infuriating because the user thinks, "What the hell do you mean read-only volume!? I launched the app from my Applications folder; it's not on a freaking disk image!"

While the message is technically correct, it's not going to appear that way to a user and it's going to produce frustration. As a result, the app in question looks dumb. Sparkle should use the translocation API to see if the read-only volume has been caused by translocation and, if so, display a better message with a link to a help page that describes what's going on. 

An example of that message could be: "[app name] cannot be updated because macOS has marked it as read-only for security reasons. Click the "Help" button for more information."

**Comment by zorgiepoo** [comment]
I don't think the APIs mentioned in your link are public anymore. I wouldn't find using private APIs or shelling out to a tool to report a different error message here to be acceptable. Also translocation is rather confusing so as far as help goes most of what you'd find online is geared towards developers, and Apple doesn't have an official document on it for users.

This is also sidestepping the issue that the app is not opting out of App Translocation and following Apple's [guidelines](https://developer.apple.com/library/content/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG17), which if it were, there'd be no need to explain translocation.

**Comment by durandom** [comment]
seems some Finder magic is involved here.

I had this problem with Bartender 2. Before I was

1. unzip app in ~/Downloads
2. move the app to ~/Applications via Alfred App
3. Launch App
4. Error message appeared

When I read

>  My users installed the app by unzipping it, then dragging it from Downloads to Applications.

I tried dragging via Finder and indeed, it solved the issue.

**Comment by pornel** [comment]
I've changed the wording in 55be13ca6faec96ba00164b37a17f5351b7b1b97

**Comment by bdkjones** [comment]
Fantastic! This is a great change. Thanks for including it.
