### ISSUE TITLE
generate_appcast should verify that updates pass signature checks

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#955]
Related to #896

**Comment by zorgiepoo** [comment]
I would personally be interested in automating:

* Verifying the DSA signature of the archive and delta patch files
* Unarchiving the archive, and see if *both* `codesign --verify --deep` and `spctl -a` pass, to better ensure archive is not corrupt and app is built properly, assuming the bundle is signed at all. (Note: Sparkle's code signature verification code does not have an option to use --deep)
* Invoke BinaryDelta apply after creating delta patches to make sure applying the patch doesn't fail

**Comment by pornel** [comment]
Yes, that sounds useful. The first two are good to have in the tool.

I'd put verification of delta updates in the delta tool itself (i.e. if you ask it to generate a delta, it guarantees it's fine).

**Comment by zorgiepoo** [comment]
Verification of the delta updates in the delta tool itself is interesting, but perhaps a moot point since generate_appcast doesn't use the delta tool, but rather invokes `createBinaryDelta()` directly (and I think the apply and create functions may want to be kept distinct...)

We don't have any code that simulates a `spctl` (gatekeeper) test. Note this in addition to deep code signature verification are both important to have here.

**Comment by pornel** [comment]
There could be a `createAndVerify` API used by both tools.

**Comment by pornel** [comment]
For verification I've meant using our code, because for purpose of updates that's what is the authority. Even if codesign/spctl is happy with it, if we have some bug/quirk, the update has to pass it. I don't mind running codesign/spctl in addition to that.

**Comment by zorgiepoo** [comment]
> For verification I've meant using our code, because for purpose of updates that's what is the authority. Even if codesign/spctl is happy with it, if we have some bug/quirk, the update has to pass it. I don't mind running codesign/spctl in addition to that.

I'm not quite following with what you're saying.

When we are dealing distribution, I'm not only interested in testing Sparkle's duty when applying an update. I am also interested as a developer that I didn't create an incorrect archive or build an app incorrectly, things that Sparkle doesn't really test for, due to compatibility or other reasons (e.g. gatekeeper is not applicable for our updating process).

We would have to write new code to simulate what `spctl`'s test does. We could potentially re-use our other verifying code by adding a deep option, that is YES when generating an appcast, NO when applying an update for compatibility reasons.

**Comment by pornel** [comment]
I think we probably agree.

I'm suggesting adding verification of signatures using Sparkle's own code for signature verification, so that authors have assurance that the updates will be accepted by Sparkle.

I'm OK with your suggestion of using codesign/spctl to assure authors the apps are accepted by macOS. I'm saying this should be done in addition, rather than instead of, using Sparkle's verification code.

I think using codesign/spctl command line is fine, no need to reimplement it natively.

**Comment by zorgiepoo** [comment]
In addition to sounds good 👍
