### ISSUE TITLE
Display release notes only for updates bigger than semver-patch

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#961]
I have two conflicting requirements:

* I want users to know about major updates/new features
* I want to minimize the amount of update popups that users see

I think a good compromise for this would be to have an option to show manual update window with release notes only if the update is significant compared to user's current version, and a silent autoupdate otherwise.

i.e. users who update from 3.3.0 to 3.3.1 would get silent automatic update. Users who update from 3.2.0 (and earlier) to 3.3.1 would get release notes window.

In practice that would involve adding basic semver understanding to the version comparator, and using it to override auto-update flag. Probably also another info.plist key to opt in into that behavior.

**Comment by zorgiepoo** [comment]
Interesting idea for the future. I think a prerequisite would be to have automatic installing of updates enabled, when they're allowed (i.e, don't need authorization).

Another thing to think about is the difference between alerting users of new installed features vs prompting the user to install a new update with major new features (latter is what you're suggesting).

**Comment by zorgiepoo** [comment]
Keep in mind the build version and the short version string can be pretty different, and parsing of the short version string should be avoided.

It also may be worthy to mention that the 'automatic downloading of updates' option is a user-facing option. I think it was initially designed such that users would have to opt into it. Eg: "I opted into automatic downloading of updates, why am I being bothered with release notes?"

**Comment by pornel** [comment]
The way I think about it is that it would enable auto-update for patch changes, and default setting for big changes.

**Comment by zorgiepoo** [comment]
Just for some relevance..

In my fork, this is the bit of code that decides when after the automatic downloading is done, if a notice should be shown immediately: https://github.com/zorgiepoo/Sparkle/blob/ui-separation-and-xpc/Sparkle/SPUAutomaticUpdateDriver.m#L133

And for controlling how often an update check should be scheduled afterwards: https://github.com/zorgiepoo/Sparkle/blob/ui-separation-and-xpc/Sparkle/SPUUpdater.m#L783

This kind of feature could rely on automatic downloading of updates needing to be enabled, and would need Sparkle to assume the short version string should be treated in a semver type manner (remember: we currently aren't doing any parsing from the short version string since it doesn't relate to the bundle version).

**Comment by zorgiepoo** [comment]
I think this should only be done for major upgrades otherwise user should be in control of automatically downloading updates.
