### ISSUE TITLE
Optionally concatenate release notes from all versions between old and new

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#985]
Users who update rarely may not see all relevant release notes.

e.g.

* 1.0.0 - old app
* 1.1.0 - big new feature
* 1.1.1 - minor bugfix

A user updating from 1.0.0 to 1.1.1 will only see "minor bugfix" release notes, but they're also getting "big new feature" without seeing the notes for it.

In cases where release notes are raw bits of HTML (i.e. not external links, or full documents with `<body>`), we could concatenate all relevant release notes to build a complete list of changes.

Related #961

**Comment by lwouis** [comment]
As demonstrated in your example, this can be a very bad communication/UX! I'd like to add that it's not just about users who update rarely. It also affect quick-to-update users if the devs are pushing small updates fast. [My project](https://github.com/lwouis/alt-tab-macos) has continuous deliver thus pushes a release on each merge on `master`. This means it's frequent to merge multiple times a day thus releasing multiple times a day. In that context, I'm affected by this issue even more.

I think as a workaround, I'll put the full changelog as the release note of each release. That way because it's top-to-bottom the user will get the latest, but then are free to scroll down as they please. I would rather should them too much info (i.e. showing releases prior to the one they have) than not enough (i.e. missing major releases as you have illustrated).

**Comment by zorgiepoo** [comment]
A single appcast item (per branch point) should be sufficient for describing the update. Not a fan of combining preceding update items.
